// ============================================================
// Permission + role catalogue (Hope Design ERP)
// Permission codes: {module}.{resource}.{action}
// ============================================================

const ACTIONS = ["view","create","update","delete","submit","approve","reject","cancel","void","archive","restore","print","export","import","scan","transfer","assign","release","convert","verify","post","generate","complete","admit","discharge","dispense","settle","terminate","delete_draft","manage_templates","manage_clauses","manage_versions","manage_legal_rules","view_audit","validate","sign","download","renew","vary","issue","manage","dispose","audit","depreciate","impair","capitalize","maintain","inspect","checkin","checkout","replace","activate","investigate","resolve","comment","reprint","perform","close","return","send","suspend","resume","revoke","expire","upload"];

const MODULES = {
  dashboard: { overview: ["view"], kpis: ["view"] },
  communication: {
    command: ["view"],
    messages: ["view", "send", "manage"],
    notifications: ["view", "read", "manage"],
    emails: ["view", "send", "manage"],
    announcements: ["view", "create", "manage"],
    templates: ["view", "manage"],
    delivery_logs: ["view"],
    settings: ["manage"],
    // Company Mailing System (migration 0169). Kept inside the existing
    // `communication` module so every current `communication.*` holder keeps a
    // single coherent mail namespace and no parallel permission module appears.
    mailboxes: ["view", "create", "update", "delete", "manage"],
    mailbox_members: ["view", "create", "update", "delete", "manage"],
    mailbox_delegations: ["view", "create", "revoke", "manage"],
    mail_drafts: ["view", "create", "update", "delete"],
    mail_scheduled: ["view", "create", "update", "cancel"],
    mail_labels: ["view", "create", "update", "delete"],
    mail_rules: ["view", "create", "update", "delete", "manage"],
    mail_signatures: ["view", "create", "update", "delete", "manage"],
    mail_distribution_lists: ["view", "create", "update", "delete", "manage"],
    mail_approvals: ["view", "submit", "approve", "reject", "manage"],
    mail_classifications: ["view", "manage"],
    mail_contacts: ["view", "export"],
    mail_attachments: ["view", "upload", "download", "delete"],
    mail_scheduler: ["view", "manage"],
    mail_providers: ["view", "manage"],
    mail_audit: ["view", "export"],
    mail_admin: ["view", "manage"],
  },
  crm: {
    leads: ["view","create","update","delete","submit","convert","assign","export","import"],
    customers: ["view","create","update","delete","submit","approve","block","export","import"],
    contacts: ["view","create","update","delete"],
    opportunities: ["view","create","update","delete","win","lose","assign"],
    activities: ["view","create","update","delete","complete"],
    complaints: ["view","create","update","delete","resolve","escalate"],
  },
  sales: {
    quotations: ["view","create","update","delete","submit","approve","reject","convert","revise","print","export","import","send"],
    orders: ["view","create","update","delete","submit","approve","reject","cancel","allocate","dispatch","print","export","import"],
    delivery_notes: ["view","create","update","submit","dispatch","deliver","confirm","print","export"],
    invoices: ["view","create","update","submit","approve","post","void","print","export"],
    receipts: ["view","create","update","post","void","print","export"],
    credit_notes: ["view","create","update","submit","approve","post","void","print","export"],
    debit_notes: ["view","create","update","submit","approve","post","void","print","export"],
    returns: ["view","create","update","approve","inspect","complete","print","export"],
    statements: ["view","print","export"],
  },
  procurement: {
    suppliers: ["view","create","update","delete","submit","approve","block","evaluate","export","import"],
    requisitions: ["view","create","update","submit","approve","reject","convert"],
    rfqs: ["view","create","update","issue","evaluate","award"],
    quotations: ["view","create","update","evaluate","select"],
    orders: ["view","create","update","submit","approve","reject","cancel","close","print","export","import"],
    goods_receipts: ["view","create","update","submit","approve","inspect","print"],
    supplier_invoices: ["view","create","update","submit","approve","match","post","void"],
    payments: ["view","create","update","submit","approve","release","post","void"],
    returns: ["view","create","update","approve","complete"],
    contracts: ["view","create","update","approve","expire"],
  },
  inventory: {
    items: ["view","create","update","delete","adjust","transfer","scan","count","export","import"],
    stock: ["view","count","adjust","transfer","export","import"],
    movements: ["view","create","export"],
    reservations: ["view","create","release","cancel"],
    adjustments: ["view","create","update","submit","approve","reject","post","cancel"],
    transfers: ["view","create","update","submit","approve","reject","complete","cancel"],
    batches: ["view","create","update","block","release"],
    bins: ["view","create","update","delete"],
    warehouses: ["view","create","update","delete"],
    zones: ["view","create","update","delete"],
    racks: ["view","create","update","delete"],
    shelves: ["view","create","update","delete"],
    ledger: ["view","export"],
    transactions: ["view","create","submit","approve","post","reverse","cancel"],
    counts: ["view","create","update","enter","approve","post","cancel","schedule"],
    quality_holds: ["view","create","update","release","reject"],
    handling_units: ["view","create","update","break","consolidate","dispatch"],
    traceability: ["view","export"],
    forecasts: ["view","create","update","override"],
    valuations: ["view","create","export"],
    alerts: ["view","acknowledge","resolve"],
    item_attributes: ["view","create","update","delete"],
    allocations: ["view","create","release","cancel"],
    reorder_recommendations: ["view","approve","convert","dismiss"],
    recalls: ["view","create","update","quarantine","close","notify"],
    risk: ["view","recalculate"],
    putaway: ["view","execute","confirm"],
    receiving: ["view","create","execute","confirm"],
    picking: ["view","create","execute","confirm"],
    packing: ["view","create","execute","confirm"],
    dispatch: ["view","create","execute","confirm"],
  },
  production: {
    plans: ["view","create","update","submit","approve","reject","execute"],
    work_orders: ["view","create","update","delete","submit","approve","reject","release","start","complete","close","issue","return","record","print"],
    boms: ["view","create","update","delete","approve"],
    routings: ["view","create","update","delete","approve"],
    work_centres: ["view","create","update","delete"],
    machines: ["view","create","update","delete","operate","maintain","assign"],
    outputs: ["view","create","update"],
    downtime: ["view","create","update"],
    costing: ["view","recalculate"],
    kpis: ["view"],
    analytics: ["view","export"],
    command: ["view"],
    ai: ["view"],
    alerts: ["view","acknowledge","resolve"],
    schedule: ["view","create","update","publish"],
    traceability: ["view","export"],
    batches: ["view","create","update","close"],
    quality_holds: ["view","create","dispose","release"],
    rework: ["view","create","approve","complete"],
    subcontract: ["view","create","approve","receive","complete"],
    shifts: ["view","create","acknowledge"],
  },
  quality: {
    plans: ["view","create","update","delete","approve"],
    inspections: ["view","create","update","submit","approve","execute","quarantine"],
    results: ["view","create","update"],
    defects: ["view","create","update"],
    ncrs: ["view","create","update","investigate","close"],
    capa: ["view","create","update","verify","close"],
  },
  security_printing: {
    jobs: ["view","create","update","delete","submit","approve","reject","authorize_materials","issue_materials","reconcile","hold","resume","dispatch","print"],
    custody: ["view","record","witness"],
    batches: ["view","create","update"],
    operators: ["view","assign"],
    machines: ["view","assign"],
    audit: ["view"],
  },
  qr: {
    codes: ["view","create","generate","void","suspend","replace","archive"],
    labels: ["view","create","print","reprint"],
    scans: ["view","perform","verify"],
    templates: ["view","create","update","delete"],
    anomalies: ["view","investigate","resolve"],
    traceability: ["view","export"],
    recalls: ["view","create","update","close"],
    reams: ["view","create","generate","print"],
    cartons: ["view","create","seal","print"],
    packing: ["scan","seal"],
  },
  maintenance: {
    requests: ["view","create","update","assign","complete"],
    schedules: ["view","create","update","delete"],
    work_orders: ["view","create","update","complete"],
  },
  logistics: {
    vehicles: ["view","create","update","delete"],
    routes: ["view","create","update","delete"],
    drivers: ["view","create","update","delete"],
    trips: ["view","create","update","complete"],
    fuel: ["view","create","update"],
    fleet: ["view","create","update"],
    deliveries: ["view","create","update","dispatch","deliver","track"],
  },
  finance: {
    chart_of_accounts: ["view","create","update","delete"],
    journals: ["view","create","post","void","export","submit","approve","reject","reverse"],
    periods: ["view","create","open","close","lock"],
    banks: ["view","create","update","reconcile"],
    kcb: ["view","manage","test"],
    equity: ["view","manage","test"],
    budgets: ["view","create","update","submit","approve","close"],
    expenses: ["view","create","update","submit","approve","post","void"],
    advances: ["view","create","settle","void"],
    taxes: ["view","create","update"],
    reports: ["view","print","export"],
    posting_rules: ["view","create","post"],
    templates: ["view","create"],
    tax_jurisdictions: ["view","create"],
    tax_rules: ["view","create"],
    tax_transactions: ["view","create"],
    efris: ["view","create","sync","cancel"],
    budget_revisions: ["view","create"],
    budget_commitments: ["view","create","release"],
    allocation_rules: ["view","create"],
    production_costs: ["view","create","post"],
    intercompany: ["view","create"],
    consolidation: ["view","run"],
    close_tasks: ["view","update"],
    audit: ["view"],
  },
  expenditure: {
    dashboards: ["view"],
    requisitions: ["view","create","update","submit","approve","fulfill","cancel"],
    expenses: ["view","create","update","submit","approve","post","void"],
    petty_cash: ["view","create","update","replenish","reconcile"],
    claims: ["view","create","approve","reimburse"],
    receipts: ["view","upload","verify"],
    payments: ["view","create","approve","post"],
    daily_close: ["view","create","approve"],
    reports: ["view"],
    settings: ["manage"],
  },
  hr: {
    employees: ["view","create","update","delete","terminate","export","import"],
    contracts: ["view","create","update","delete_draft","terminate","validate","submit","approve","reject","sign","download","export","renew","vary","generate","manage_templates","manage_clauses","manage_versions","manage_legal_rules","view_audit"],
    certificates: ["view","create","update","issue","download","export"],
    legal_rules: ["view","manage"],
    // Organization management
    divisions: ["view","create","update","delete"],
    locations: ["view","create","update","delete"],
    org_units: ["view","create","update","delete"],
    teams: ["view","create","update","delete"],
    job_families: ["view","create","update","delete"],
    job_grades: ["view","create","update","delete"],
    positions: ["view","create","update","delete","assign"],
    position_assignments: ["view","create","update","delete"],
    // Workforce planning
    workforce_plans: ["view","create","update","submit","approve","reject","delete"],
    workforce_scenarios: ["view","create","update","delete","simulate"],
    // Recruitment / ATS
    requisitions: ["view","create","update","submit","approve","reject","cancel","delete"],
    vacancies: ["view","create","update","publish","unpublish","close","cancel","delete"],
    vacancy_channels: ["view","create","update","delete"],
    candidates: ["view","create","update","delete","import","export"],
    applications: ["view","create","update","submit","shortlist","advance","withdraw","reject"],
    interviews: ["view","create","update","complete","cancel"],
    assessments: ["view","create","update","complete"],
    offers: ["view","create","update","send","accept","decline","withdraw","expire"],
    onboarding: ["view","create","update","start","complete","cancel","delete"],
    attendance: ["view","create","update","export","review","approve","reject","lock","create_adjustment","view_own"],
    shifts: ["view","create","update","delete","assign"],
    shift_assignments: ["view","create","update","delete"],
    timesheets: ["view","create","update","submit","approve","reject"],
    overtime: ["view","create","update","approve","reject"],
    leave: ["view","create","update","approve","reject"],
    leave_types: ["view","create","update","delete"],
    leave_policies: ["view","create","update","delete"],
    leave_accruals: ["view","create","update","accrue"],
    leave_balances: ["view","update"],
    holidays: ["view","create","update","delete"],
    // Performance
    performance_goals: ["view","create","update","delete","complete"],
    performance_kpis: ["view","create","update","delete"],
    performance_reviews: ["view","create","update","submit","approve","reject","complete"],
    pips: ["view","create","update","submit","approve","close"],
    // Learning & development
    training_catalog: ["view","create","update","delete"],
    training_sessions: ["view","create","update","delete","complete"],
    training_requests: ["view","create","update","submit","approve","reject"],
    training_enrollments: ["view","create","update","delete"],
    training_certificates: ["view","create","update","issue"],
    competencies: ["view","create","update","delete"],
    // Benefits
    benefit_plans: ["view","create","update","delete"],
    benefit_enrollments: ["view","create","update","delete","enroll"],
    benefit_claims: ["view","create","update","submit","approve","reject"],
    // Employee relations
    grievances: ["view","create","update","submit","investigate","resolve","close"],
    investigations: ["view","create","update","start","complete"],
    disciplinary: ["view","create","update","submit","investigate","decide","appeal","close"],
    warnings: ["view","create","update","issue","expire"],
    // HR asset assignments
    asset_assignments: ["view","create","update","return","delete"],
    // Employee identity / ID cards
    employee_assignments: ["view","create"],
    employee_identity: ["view","generate","replace","suspend"],
    employee_card: ["view","generate","issue","print","replace","suspend"],
    employee_qr: ["view","generate","scan","verify"],
    // Offboarding / alumni (exit lifecycle)
    offboardings: ["view","create","update","start","complete","cancel","waive","export"],
    alumni: ["view","export"],
    // Payroll configuration
    payroll_components: ["view","create","update","delete"],
    employee_salaries: ["view","create","update","delete"],
    employee_earnings: ["view","create","update","delete","submit","approve","reject"],
    employee_deductions: ["view","create","update","delete","submit","approve","reject"],
    employee_benefits: ["view","create","update","delete"],
    overtime_records: ["view","create","update","approve","reject"],
    bonus_records: ["view","create","update","approve","reject"],
    commission_records: ["view","create","update","approve","reject"],
    statutory_configs: ["view","create","update","delete","activate"],
    payroll_settings: ["view","create","update","delete","archive","restore"],
    payroll_periods: ["view","create","update","close"],
    statutory: ["view","create","update","approve"],
    payroll_exceptions: ["view","resolve"],
    employee_payroll: ["self_view"],
    // Self-service
    employee_requests: ["view","create","update","cancel"],
    projects: ["view","create","update","delete"],
    // Legacy aliases kept for compatibility
    recruitment: ["view","create","update"],
    training: ["view","create","update"],
    performance: ["view","create","update"],
    payrolls: ["view","create","update","calculate","validate","submit","review","approve","release","post","pay","close","reopen","export","void","print"],
    payslips: ["view","print","send","generate"],
    loans: ["view","create","update","approve","reject","pause","write_off"],
      advances: ["view","create","update","approve","reject"],
    final_settlements: ["view","create","update","submit","approve","reject","pay","export"],
  },
  healthcare: {
    facilities: ["view","create","update","delete","print","export","import"],
    wards: ["view","create","update","delete","assign"],
    beds: ["view","create","update","delete","assign","release"],
    practitioners: ["view","create","update","delete","assign","print","export","import"],
    patients: ["view","create","update","delete","admit","discharge","print","export","import","scan"],
    visits: ["view","create","update","delete","submit","admit","discharge","complete","print","export","import"],
    appointments: ["view","create","update","delete","submit","approve","reject","complete","print","export"],
    emrs: ["view","create","update","delete","complete","print","export","import"],
    diagnoses: ["view","create","update","delete"],
    vitals: ["view","create","update"],
    observations: ["view","create","update"],
    prescriptions: ["view","create","update","delete","submit","approve","reject","dispense","print","export"],
    dispensings: ["view","create","update","complete","print","export"],
    lab_requests: ["view","create","update","delete","submit","approve","complete","print","export"],
    lab_results: ["view","create","update","complete","print","export"],
    insurance_payers: ["view","create","update","delete","approve"],
    insurance_claims: ["view","create","update","submit","approve","reject","settle","print","export"],
    bills: ["view","create","update","submit","approve","post","print","export"],
  },
  assets: {
    register: ["view","create","update","delete","submit","approve","reject","dispose","transfer","audit","print","export","import","capitalize","depreciate","impair","assign","verify","scan","maintain","inspect","checkin","checkout","restore","archive","comment"],
    tags: ["view","create","generate","print","reprint","replace","void","archive"],
    transfers: ["view","create","update","submit","approve","reject","complete","cancel"],
    movements: ["view","create"],
    assignments: ["view","create","complete","return","cancel"],
    audits: ["view","create","update","submit","approve","close","cancel"],
    audit_items: ["view","create","update"],
    maintenance: ["view","create","update","submit","approve","complete","cancel"],
    disposals: ["view","create","update","submit","approve","reject","complete","cancel"],
    locations: ["view","create","update","delete"],
    categories: ["view","create","update","delete"],
    types: ["view","create","update","delete"],
    classes: ["view","create","update","delete"],
    warranties: ["view","create","update","delete"],
    insurance: ["view","create","update","delete"],
    documents: ["view","create","update","delete","download"],
    photos: ["view","create","delete"],
    depreciation: ["view","create","post"],
    impairments: ["view","create","submit","approve","reject","post"],
    scans: ["view","perform","verify"],
    anomalies: ["view","investigate","resolve"],
    custodians: ["view"],
    timeline: ["view"],
    dashboards: ["view"],
    reports: ["view","export"],
    imports: ["view","create"],
    exports: ["view","create"],
    settings: ["view","update"],
  },
  documents: {
    documents: ["view","create","update","delete","approve","archive","restore","download","sign"],
    versions: ["view","create"],
  },
  workflows: {
    workflows: ["view","create","update","delete","activate"],
    instances: ["view","approve","reject","return","delegate","escalate","cancel"],
  },
  notifications: { notifications: ["view","read"], tasks: ["view","create","update","complete"] },
  reports: {
    dashboards: ["view","create","update","delete"],
    executive: ["view"],
    sales: ["view","export"],
    procurement: ["view","export"],
    inventory: ["view","export"],
    production: ["view","export"],
    quality: ["view","export"],
    finance: ["view","export"],
    hr: ["view","export"],
    healthcare: ["view","export"],
    qr: ["view","export"],
    security: ["view","export"],
    logistics: ["view","export"],
    kpis: ["view","create","update","delete","measure"],
    builder: ["view","create","update","delete","run"],
    saved: ["view","create","update","delete","schedule"],
  },
  // Organisation Settings is the ERP control plane: one module whose resources
  // are the settings categories an administrator may configure. Read access is
  // deliberately separate from per-domain "manage".
  organisation: {
    settings: ["view","create","update","delete"],
    structure: ["manage"],
    tax: ["manage"],
    finance: ["manage"],
    payroll: ["manage"],
    documents: ["manage"],
    security: ["manage"],
    integrations: ["manage"],
    qr: ["manage"],
    manufacturing: ["manage"],
    inventory: ["manage"],
    hr: ["manage"],
    attendance: ["manage"],
    audit: ["view"],
  },
  admin: {
    users: ["view","create","update","delete","disable","enable","reset_password","assign_roles","activate","suspend","invite","view_sessions","revoke_sessions"],
    roles: ["view","create","update","delete"],
    permissions: ["view","assign"],
    policies: ["view","create","update","delete","activate"],
    sod: ["view","create","update","delete","activate"],
    settings: ["view","update"],
    imports: ["view","run","download_template"],
    exports: ["view","run"],
    audit: ["view","export"],
    events: ["view"],
    dashboard: ["view"],
    sessions: ["view","revoke"],
    security: ["view"],
    feature_flags: ["view","update"],
    backups: ["view","restore"],
    health: ["view"],
    audit_logs: ["view"],
    company_config: ["administer","update","view"],
    integrations: ["manage","view"],
    notifications: ["update","view"],
    numbering: ["update","view"],
    organization: ["update","view"],
  },
  database: {
    health: ["view"],
    connections: ["view"],
    activity: ["view"],
    performance: ["view"],
    query: ["analyze"],
    schema: ["view","manage"],
    index: ["view","manage"],
    backup: ["view","create","delete"],
    restore: ["request","approve"],
    migration: ["view","execute"],
    integrity: ["run"],
    data_quality: ["view"],
    retention: ["manage"],
    archive: ["manage"],
    audit: ["view"],
    settings: ["manage"],
    locks: ["view"],
    maintenance: ["run"],
  },
  governance: {
    delegations: ["view","create","update","submit","approve","reject","suspend","resume","revoke","expire","cancel"],
    delegation_authorities: ["view","create","update","delete"],
    acting_roles: ["view","export"],
    signature_profiles: ["view","create","update","submit","approve","reject","activate","suspend","revoke","expire","upload"],
    signature_authority_scopes: ["view","create","update","delete","approve"],
    document_signatures: ["view","create","verify","export"],
  },
  efris: {
    dashboard: ["view"],
    transactions: ["view","submit","retry","reprocess","reject"],
    configuration: ["view","manage"],
    reconciliation: ["view","manage"],
    credit_notes: ["view","create","approve"],
    debit_notes: ["view","create","approve"],
    reports: ["view","export"],
    errors: ["view","retry","archive"],
  },
  hikvision: {
    command: ["view"],
    dashboard: ["view"],
    devices: ["view","create","update","delete"],
    events: ["view","retry","reprocess","reject"],
    exceptions: ["view","assign","resolve","approve","reject"],
    sync: ["view","employee","bulk","remove_access"],
    configuration: ["view","manage"],
    health: ["view"],
    reports: ["view","export"],
    employee_links: ["view","create","update","delete"],
  },
  // ---------------------------------------------------------------
  // HOPE DESIGN Service Desk & ITSM
  // ---------------------------------------------------------------
  service_desk: {
    command: ["view"],
    tickets: ["view","view_own","create","create_on_behalf","update","delete","reply","assign","resolve","close","close_own","reopen","escalate","export","import","print","verify"],
    internal_notes: ["view","create"],
    queues: ["view","create","update","delete"],
    teams: ["view","create","update","delete"],
    skills: ["view","create","update","delete"],
    categories: ["view","create","update","delete"],
    sla: ["view","manage"],
    escalations: ["view","create","update","delete","manage"],
    service_requests: ["view","create","update","approve","reject","fulfil","cancel"],
    incidents: ["view","create","update","resolve","close","escalate"],
    problems: ["view","create","update","investigate","resolve","close"],
    known_errors: ["view","create","update","resolve","archive"],
    changes: ["view","create","update","submit","approve","reject","implement","validate","close","cancel"],
    change_approvals: ["view","create","approve","reject"],
    access_requests: ["view","view_own","create","update","approve","reject","grant","revoke","cancel"],
    knowledge: ["view","create","update","delete","submit","approve","publish","archive","rate","manage"],
    asset_scans: ["view","scan","report"],
    assets: ["view"],
    dashboards: ["employee","agent","manager","executive"],
    reports: ["view","export"],
    settings: ["view","manage"],
    audit: ["view"],
  },
  // ---------------------------------------------------------------
  // Personal Data Protection Office (PDPO) compliance register
  // ---------------------------------------------------------------
  compliance: {
    pdpo: ["view","manage","file","export"],
    processing_activities: ["view","create","update","delete"],
    consents: ["view","create","withdraw","delete"],
    subject_requests: ["view","create","update","fulfil","refuse"],
    breaches: ["view","create","update","report","close"],
  },
};

// Module-level permissions that do not follow the {module}.{resource}.{action}
// shape, together with the flat `documents.*` codes the Document Management
// module checks. Declared explicitly so RBAC checks such as `service_desk.admin`
// resolve, and so the `service_desk.*` and `documents.*` wildcards pick them up.
const EXTRA_PERMISSIONS = [
  {
    code: "service_desk.admin",
    module: "service_desk",
    resource: "admin",
    action: "admin",
    description: "Administer the HOPE DESIGN Service Desk (taxonomy, queues, SLAs, escalation, settings)",
  },
  // Flat document codes (introduced by migration 0116). The documents routes and
  // nav check these exact codes, so they have to exist in the catalogue for a
  // `documents.*` grant to resolve to anything and for reconcileRbac to keep
  // their permission rows alive across re-seeds.
  { code: "documents.command.view", module: "documents", resource: "command", action: "view", description: "View the document command centre" },
  { code: "documents.view", module: "documents", resource: "library", action: "view", description: "View documents in the library" },
  { code: "documents.create", module: "documents", resource: "library", action: "create", description: "Create documents" },
  { code: "documents.edit", module: "documents", resource: "library", action: "edit", description: "Edit document metadata" },
  { code: "documents.upload", module: "documents", resource: "library", action: "upload", description: "Upload document files and new versions" },
  { code: "documents.download", module: "documents", resource: "library", action: "download", description: "Download document files" },
  { code: "documents.approve", module: "documents", resource: "library", action: "approve", description: "Approve, reject and release documents" },
  { code: "documents.delete", module: "documents", resource: "library", action: "delete", description: "Delete or archive documents" },
  { code: "documents.folders.manage", module: "documents", resource: "folders", action: "manage", description: "Manage document folders" },
  { code: "documents.settings.manage", module: "documents", resource: "settings", action: "manage", description: "Configure document management settings" },
  // Flat cron codes (introduced by migration 0118). The admin cron routes and the
  // Communication -> Cron Jobs tab check these exact codes, so they have to exist in
  // the catalogue for a `system.*` grant to resolve to anything, and for reconcileRbac
  // to keep their permission rows alive across re-seeds.
  { code: "system.cron.view", module: "system", resource: "cron", action: "view", description: "View cron jobs and run history" },
  { code: "system.cron.manage", module: "system", resource: "cron", action: "manage", description: "Create, edit, toggle and manually run cron jobs" },
];

function buildPermissions() {
  const perms = [];
  for (const [module, resources] of Object.entries(MODULES)) {
    for (const [resource, actions] of Object.entries(resources)) {
      for (const action of actions) {
        perms.push({
          code: `${module}.${resource}.${action}`,
          module,
          resource,
          action,
          description: `${action} ${resource} (${module})`,
          is_system: false,
        });
      }
    }
  }
  for (const p of EXTRA_PERMISSIONS) {
    perms.push({ ...p, is_system: false });
  }
  return perms;
}

// Role catalogue per the ERP spec (section 9).
// grants use wildcards: "*" = everything, "module.*" = module, "module.resource.*" = resource.
const ROLES = [
  // Administration
  { code: "super_administrator", name: "Super Administrator", grants: ["*"] },
  { code: "system_administrator", name: "System Administrator", grants: ["efris.configuration.manage","efris.dashboard.view","efris.transactions.view","efris.transactions.retry","efris.transactions.reprocess","efris.transactions.reject","efris.reconciliation.view","efris.errors.view","efris.errors.retry","efris.reports.view", "admin.*", "database.*", "settings", "workflows.*", "reports.*", "expenditure.*", "communication.*", "hikvision.*","governance.delegations.view","governance.signature_profiles.view","governance.document_signatures.view","governance.document_signatures.verify","compliance.pdpo.view","compliance.pdpo.export","compliance.processing_activities.view","compliance.consents.view","compliance.subject_requests.view","compliance.breaches.view"] },
  { code: "security_administrator", name: "Security Administrator", grants: ["efris.dashboard.view","efris.transactions.view","efris.configuration.view","efris.reconciliation.view","efris.errors.view","efris.reports.view", "admin.users.*", "admin.roles.*", "admin.permissions.*", "admin.policies.*", "admin.sod.*", "admin.audit.*", "qr.*", "security_printing.audit.*", "hikvision.*","governance.delegations.view","governance.delegations.revoke","governance.signature_profiles.view","governance.signature_profiles.revoke","governance.document_signatures.view","governance.document_signatures.verify","compliance.pdpo.view","compliance.pdpo.export","compliance.processing_activities.view","compliance.consents.view","compliance.subject_requests.view","compliance.breaches.view","compliance.breaches.create","compliance.breaches.update","compliance.breaches.report","compliance.breaches.close"] },
  { code: "it_support_administrator", name: "IT Support Administrator", grants: ["admin.users.view", "admin.settings.*", "documents.*"] },
  { code: "integration_administrator", name: "Integration Administrator", grants: ["efris.configuration.manage","efris.dashboard.view","efris.transactions.view","efris.transactions.retry","efris.transactions.reprocess","efris.transactions.reject","efris.reconciliation.view","efris.errors.view","efris.errors.retry","efris.reports.view", "admin.imports.*", "admin.exports.*", "admin.events.*", "admin.integrations.*", "admin.settings.view", "hikvision.*"] },
  { code: "backup_administrator", name: "Backup Administrator", grants: ["admin.settings.view", "admin.audit.view"] },
  { code: "audit_administrator", name: "Audit Administrator", grants: ["admin.audit.*", "admin.events.*", "reports.*", "compliance.pdpo.view", "compliance.pdpo.export", "compliance.processing_activities.view", "compliance.consents.view", "compliance.subject_requests.view", "compliance.breaches.view"] },
  { code: "data_protection_officer", name: "Data Protection Officer", grants: ["compliance.*", "reports.*", "admin.audit.view", "governance.delegations.view"] },
  // Executive
  { code: "ceo", name: "CEO", grants: ["*", "!admin.users.*", "!admin.roles.*", "!admin.permissions.*", "!admin.policies.*", "!admin.sod.*", "!admin.security.*", "!admin.sessions.*"] },
  { code: "managing_director", name: "Managing Director", grants: ["*", "!admin.users.*", "!admin.roles.*", "!admin.permissions.*", "!admin.policies.*", "!admin.sod.*", "!admin.security.*", "!admin.sessions.*"] },
  { code: "executive_director", name: "Executive Director", grants: ["*", "!admin.users.*", "!admin.roles.*", "!admin.permissions.*", "!admin.policies.*", "!admin.sod.*", "!admin.security.*", "!admin.sessions.*"] },
  { code: "general_manager", name: "General Manager", grants: ["*", "!admin.users.*", "!admin.roles.*", "!admin.permissions.*", "!admin.policies.*", "!admin.sod.*", "!admin.security.*", "!admin.sessions.*"] },
  { code: "operations_director", name: "Operations Director", grants: ["production.*", "quality.*", "maintenance.*", "inventory.*", "procurement.*", "expenditure.*", "workflows.instances.*", "reports.*", "communication.command.view", "communication.notifications.*", "communication.delivery_logs.view","governance.delegations.view","governance.acting_roles.view","governance.document_signatures.view","governance.document_signatures.create","governance.document_signatures.verify"] },
  { code: "cfo", name: "CFO", grants: ["efris.*", "finance.*", "expenditure.*", "procurement.payments.*", "workflows.instances.*", "reports.finance.*", "reports.executive.*", "hr.final_settlements.view", "hr.final_settlements.approve", "hr.final_settlements.pay", "hr.final_settlements.export", "communication.command.view", "communication.notifications.*", "communication.delivery_logs.view"] },
  { code: "commercial_director", name: "Commercial Director", grants: ["crm.*", "sales.*", "expenditure.*", "reports.sales.*", "reports.executive.*", "communication.*"] },
  { code: "hr_director", name: "HR Director", grants: ["hr.*", "reports.hr.*", "reports.dashboards.view", "communication.*", "hikvision.*","governance.*","compliance.processing_activities.view","compliance.processing_activities.create","compliance.processing_activities.update","compliance.consents.view","compliance.consents.create","compliance.consents.withdraw","compliance.subject_requests.view","compliance.subject_requests.create","compliance.subject_requests.update","compliance.subject_requests.fulfil","compliance.subject_requests.refuse"] },
  // Finance
  { code: "finance_manager", name: "Finance Manager", grants: ["efris.*", "finance.*", "expenditure.*", "procurement.supplier_invoices.*", "procurement.payments.*", "workflows.instances.*", "reports.finance.*", "hr.final_settlements.view", "hr.final_settlements.approve", "hr.final_settlements.pay"] },
  { code: "chief_accountant", name: "Chief Accountant", grants: ["efris.*", "finance.*", "expenditure.*", "workflows.instances.*", "reports.finance.*"] },
  { code: "financial_controller", name: "Financial Controller", grants: ["efris.*", "finance.*", "reports.finance.*", "procurement.supplier_invoices.view", "sales.invoices.view"] },
  { code: "accountant", name: "Accountant", grants: ["efris.dashboard.view","efris.transactions.view","efris.transactions.submit","efris.transactions.retry","efris.transactions.reprocess","efris.reconciliation.view","efris.credit_notes.view","efris.credit_notes.create","efris.debit_notes.view","efris.debit_notes.create","efris.reports.view","efris.reports.export","efris.errors.view","efris.errors.retry", "finance.chart_of_accounts.*", "finance.journals.*", "finance.banks.*", "finance.expenses.*", "finance.advances.*", "finance.taxes.*", "finance.periods.view", "finance.reports.view", "finance.posting_rules.*", "finance.templates.*", "finance.tax_jurisdictions.*", "finance.tax_rules.*", "finance.tax_transactions.*", "finance.efris.*", "finance.budget_revisions.view", "finance.budget_commitments.view", "finance.allocation_rules.*", "finance.production_costs.*", "finance.intercompany.view", "finance.consolidation.view", "finance.close_tasks.view", "finance.audit.view"] },
  { code: "ar_officer", name: "AR Officer", grants: ["efris.dashboard.view","efris.transactions.view","efris.reconciliation.view","efris.credit_notes.view","efris.credit_notes.create","efris.debit_notes.view","efris.debit_notes.create", "sales.invoices.*", "sales.receipts.*", "sales.credit_notes.*", "sales.debit_notes.*", "sales.statements.*", "finance.banks.view", "finance.journals.view", "reports.finance.view"] },
  { code: "ap_officer", name: "AP Officer", grants: ["procurement.supplier_invoices.*", "procurement.payments.view", "finance.banks.view", "finance.journals.view"] },
  { code: "cashier", name: "Cashier", grants: ["sales.receipts.view", "sales.receipts.create", "sales.receipts.post", "finance.banks.view", "finance.journals.view"] },
  { code: "treasury_officer", name: "Treasury Officer", grants: ["efris.dashboard.view","efris.transactions.view","efris.reconciliation.view","efris.reports.view","efris.errors.view", "finance.banks.*", "finance.journals.view", "procurement.payments.view", "sales.receipts.view", "finance.efris.view", "finance.intercompany.*", "finance.consolidation.view", "finance.production_costs.view", "finance.close_tasks.view", "finance.tax_transactions.view"] },
  { code: "budget_officer", name: "Budget Officer", grants: ["finance.budgets.*", "finance.budget_revisions.*", "finance.budget_commitments.*", "finance.posting_rules.view", "finance.reports.view", "reports.finance.view"] },
  { code: "tax_officer", name: "Tax Officer", grants: ["efris.dashboard.view","efris.transactions.view","efris.transactions.submit","efris.transactions.retry","efris.transactions.reprocess","efris.configuration.view","efris.reconciliation.view","efris.credit_notes.view","efris.credit_notes.create","efris.debit_notes.view","efris.debit_notes.create","efris.reports.view","efris.reports.export","efris.errors.view","efris.errors.retry", "finance.taxes.*", "finance.reports.*", "finance.tax_jurisdictions.*", "finance.tax_rules.*", "finance.tax_transactions.*", "finance.efris.*", "finance.journals.view"] },
  { code: "payroll_accountant", name: "Payroll Accountant", grants: ["hr.payrolls.*", "hr.employees.view", "hr.leave.view", "finance.journals.view"] },
  { code: "internal_auditor", name: "Internal Auditor", grants: ["efris.dashboard.view","efris.transactions.view","efris.configuration.view","efris.reconciliation.view","efris.credit_notes.view","efris.debit_notes.view","efris.reports.view","efris.reports.export","efris.errors.view", "admin.audit.*", "finance.reports.*", "inventory.stock.view", "procurement.orders.view", "sales.invoices.view", "reports.*", "finance.audit.view", "finance.journals.view", "finance.efris.view", "finance.tax_transactions.view", "finance.production_costs.view", "finance.close_tasks.view", "finance.consolidation.view", "compliance.pdpo.view", "compliance.pdpo.export", "compliance.processing_activities.view", "compliance.consents.view", "compliance.subject_requests.view", "compliance.breaches.view"] },
  // Sales / CRM
  { code: "sales_director", name: "Sales Director", grants: ["crm.*", "sales.*", "reports.sales.*"] },
  { code: "sales_manager", name: "Sales Manager", grants: ["crm.*", "sales.quotations.*", "sales.orders.*", "sales.delivery_notes.*", "sales.returns.*", "workflows.instances.*", "reports.sales.view", "communication.command.view", "communication.emails.*", "communication.notifications.*", "communication.delivery_logs.view"] },
  { code: "sales_executive", name: "Sales Executive", grants: ["crm.leads.*", "crm.customers.*", "crm.contacts.*", "crm.opportunities.*", "crm.activities.*", "sales.quotations.view", "sales.quotations.create", "sales.quotations.submit", "sales.quotations.print", "sales.quotations.send", "sales.orders.view"] },
  { code: "sales_representative", name: "Sales Representative", grants: ["crm.leads.view", "crm.leads.create", "crm.leads.update", "crm.activities.*", "crm.customers.view"] },
  { code: "crm_manager", name: "CRM Manager", grants: ["crm.*", "reports.sales.view"] },
  { code: "crm_officer", name: "CRM Officer", grants: ["crm.leads.*", "crm.customers.view", "crm.contacts.*", "crm.activities.*"] },
  { code: "account_manager", name: "Account Manager", grants: ["crm.customers.view", "crm.contacts.*", "crm.activities.*", "crm.complaints.*", "sales.orders.view", "sales.invoices.view"] },
  { code: "customer_service_officer", name: "Customer Service Officer", grants: ["crm.customers.view", "crm.contacts.*", "crm.complaints.*", "crm.activities.*"] },
  { code: "sales_coordinator", name: "Sales Coordinator", grants: ["sales.quotations.view", "sales.orders.view", "sales.delivery_notes.view", "crm.activities.*"] },
  // Procurement
  { code: "procurement_director", name: "Procurement Director", grants: ["procurement.*", "reports.procurement.*"] },
  { code: "procurement_manager", name: "Procurement Manager", grants: ["procurement.*", "expenditure.*", "workflows.instances.*"] },
  { code: "procurement_officer", name: "Procurement Officer", grants: ["procurement.suppliers.*", "procurement.requisitions.*", "procurement.rfqs.*", "procurement.quotations.*", "procurement.orders.create", "procurement.orders.update", "procurement.orders.submit", "procurement.orders.print", "procurement.contracts.*"] },
  { code: "purchasing_officer", name: "Purchasing Officer", grants: ["procurement.requisitions.*", "procurement.orders.view", "procurement.orders.create", "procurement.orders.submit", "procurement.rfqs.*"] },
  { code: "procurement_assistant", name: "Procurement Assistant", grants: ["procurement.requisitions.view", "procurement.rfqs.view", "procurement.orders.view"] },
  { code: "supplier_relationship_manager", name: "Supplier Relationship Manager", grants: ["procurement.suppliers.*", "procurement.contracts.*", "procurement.supplier_invoices.view"] },
  { code: "procurement_evaluator", name: "Procurement Evaluator", grants: ["procurement.quotations.evaluate", "procurement.quotations.select", "procurement.suppliers.evaluate", "procurement.rfqs.view"] },
  { code: "procurement_approver", name: "Procurement Approver", grants: ["procurement.orders.view", "procurement.orders.approve", "procurement.requisitions.view", "procurement.requisitions.approve", "procurement.suppliers.view", "procurement.suppliers.approve"] },
  // Warehouse
  { code: "supply_chain_manager", name: "Supply Chain Manager", grants: ["inventory.*", "procurement.*", "logistics.*", "reports.inventory.*"] },
  { code: "warehouse_manager", name: "Warehouse Manager", grants: ["inventory.*", "logistics.deliveries.*", "workflows.instances.*", "quality.inspections.view", "procurement.orders.view", "procurement.goods_receipts.view", "procurement.goods_receipts.create", "sales.orders.view", "sales.orders.allocate", "sales.orders.dispatch", "sales.delivery_notes.view", "production.work_orders.view", "production.work_orders.issue"] },
  { code: "warehouse_supervisor", name: "Warehouse Supervisor", grants: ["inventory.items.*", "inventory.stock.*", "inventory.movements.*", "inventory.transfers.*", "inventory.adjustments.submit", "inventory.bins.*", "qr.scan.*", "procurement.goods_receipts.view", "sales.orders.view", "production.work_orders.view", "inventory.counts.*", "inventory.quality_holds.view", "inventory.quality_holds.create", "inventory.handling_units.*", "inventory.allocations.*", "inventory.ledger.view", "inventory.traceability.view", "inventory.alerts.view", "inventory.alerts.acknowledge", "inventory.putaway.*", "inventory.receiving.*", "inventory.picking.*", "inventory.packing.*", "inventory.dispatch.*", "inventory.zones.view", "inventory.racks.view", "inventory.shelves.view"] },
  { code: "storekeeper", name: "Storekeeper", grants: ["inventory.items.view", "inventory.stock.view", "inventory.movements.create", "inventory.reservations.*", "inventory.bins.view", "qr.scan.*", "inventory.transfers.view", "procurement.goods_receipts.view", "sales.orders.view", "inventory.ledger.view", "inventory.counts.view", "inventory.counts.create", "inventory.counts.enter", "inventory.handling_units.view", "inventory.traceability.view", "inventory.alerts.view", "inventory.putaway.execute", "inventory.putaway.confirm", "inventory.receiving.view", "inventory.picking.execute", "inventory.packing.execute", "inventory.dispatch.view"] },
  { code: "inventory_controller", name: "Inventory Controller", grants: ["inventory.items.*", "inventory.stock.*", "inventory.batches.*", "inventory.reservations.*", "inventory.adjustments.view", "reports.inventory.view", "inventory.ledger.view", "inventory.counts.view", "inventory.counts.schedule", "inventory.valuations.view", "inventory.forecasts.view", "inventory.risk.view", "inventory.alerts.view", "inventory.traceability.view", "inventory.reorder_recommendations.view"] },
  { code: "inventory_officer", name: "Inventory Officer", grants: ["inventory.items.*", "inventory.stock.*", "inventory.movements.*", "inventory.batches.*"] },
  { code: "receiving_officer", name: "Receiving Officer", grants: ["procurement.goods_receipts.*", "inventory.items.view", "inventory.stock.view", "qr.scan.*"] },
  { code: "dispatch_officer", name: "Dispatch Officer", grants: ["sales.delivery_notes.*", "logistics.deliveries.*", "inventory.stock.view", "qr.scan.*", "qr.codes.view"] },
  { code: "stock_auditor", name: "Stock Auditor", grants: ["inventory.stock.view", "inventory.adjustments.*", "inventory.movements.view", "reports.inventory.view", "admin.audit.view"] },
  { code: "stock_counter", name: "Stock Counter", grants: ["inventory.stock.view", "inventory.adjustments.create", "inventory.adjustments.submit", "qr.scan.*"] },
  // Production
  { code: "production_director", name: "Production Director", grants: ["production.*", "quality.*", "maintenance.*", "inventory.stock.view", "reports.production.*"] },
  { code: "production_manager", name: "Production Manager", grants: ["production.*", "quality.inspections.view", "maintenance.requests.*", "reports.production.view"] },
  { code: "production_planner", name: "Production Planner", grants: ["production.plans.*", "production.work_orders.view", "production.work_orders.create", "production.work_orders.submit", "production.boms.view", "production.routings.view", "inventory.stock.view", "demand"] },
  { code: "production_supervisor", name: "Production Supervisor", grants: ["production.work_orders.*", "production.outputs.*", "production.downtime.*", "production.machines.view", "quality.inspections.execute", "inventory.items.view", "inventory.movements.create"] },
  { code: "production_officer", name: "Production Officer", grants: ["production.work_orders.view", "production.work_orders.update", "production.outputs.*", "production.downtime.*"] },
  { code: "work_order_manager", name: "Work Order Manager", grants: ["production.work_orders.*", "production.plans.view", "production.costing.view"] },
  { code: "production_scheduler", name: "Production Scheduler", grants: ["production.plans.*", "production.work_orders.view", "production.work_orders.update", "production.machines.view"] },
  { code: "machine_operator", name: "Machine Operator", grants: ["production.work_orders.view", "production.work_orders.start", "production.work_orders.record", "production.outputs.create", "production.downtime.create", "production.machines.view", "qr.scan.*", "quality.inspections.view"] },
  { code: "production_cost_analyst", name: "Production Cost Analyst", grants: ["production.costing.*", "production.work_orders.view", "reports.production.*"] },
  // Maintenance
  { code: "maintenance_manager", name: "Maintenance Manager", grants: ["maintenance.*", "production.machines.view", "inventory.items.view"] },
  { code: "maintenance_supervisor", name: "Maintenance Supervisor", grants: ["maintenance.*", "production.machines.view"] },
  { code: "maintenance_technician", name: "Maintenance Technician", grants: ["maintenance.requests.view", "maintenance.requests.update", "maintenance.work_orders.*", "production.machines.view", "qr.scan.*"] },
  { code: "electrical_technician", name: "Electrical Technician", grants: ["maintenance.work_orders.*", "maintenance.requests.view", "production.machines.view"] },
  { code: "mechanical_technician", name: "Mechanical Technician", grants: ["maintenance.work_orders.*", "maintenance.requests.view", "production.machines.view"] },
  { code: "machine_controller", name: "Machine Controller", grants: ["production.machines.*", "maintenance.requests.*", "maintenance.schedules.view"] },
  { code: "maintenance_planner", name: "Maintenance Planner", grants: ["maintenance.schedules.*", "maintenance.requests.view", "production.machines.view"] },
  // Quality
  { code: "quality_director", name: "Quality Director", grants: ["quality.*", "production.work_orders.view", "reports.quality.*"] },
  { code: "quality_manager", name: "Quality Manager", grants: ["quality.*", "production.work_orders.view", "reports.quality.view"] },
  { code: "quality_supervisor", name: "Quality Supervisor", grants: ["quality.plans.*", "quality.inspections.*", "quality.defects.*", "quality.ncrs.*", "quality.capa.*"] },
  { code: "quality_inspector", name: "Quality Inspector", grants: ["quality.inspections.*", "quality.results.*", "quality.defects.*", "quality.ncrs.view", "qr.scan.*", "inventory.stock.view"] },
  { code: "qc_officer", name: "QC Officer", grants: ["quality.inspections.view", "quality.inspections.execute", "quality.results.*", "quality.defects.*"] },
  { code: "ncr_officer", name: "NCR Officer", grants: ["quality.ncrs.*", "quality.capa.*"] },
  { code: "qa_auditor", name: "QA Auditor", grants: ["quality.inspections.view", "quality.ncrs.view", "quality.capa.view", "reports.quality.view", "admin.audit.view"] },
  // Security printing
  { code: "security_printing_director", name: "Security Printing Director", grants: ["security_printing.*", "qr.*", "quality.*", "reports.security.*"] },
  { code: "security_printing_manager", name: "Security Printing Manager", grants: ["security_printing.*", "qr.codes.*", "qr.labels.*", "qr.reams.*", "qr.cartons.*", "qr.packing.*", "reports.security.view"] },
  { code: "security_production_supervisor", name: "Security Production Supervisor", grants: ["security_printing.jobs.*", "security_printing.custody.*", "security_printing.batches.*", "security_printing.operators.*", "security_printing.machines.*", "qr.scan.*", "qr.packing.*"] },
  { code: "security_printing_officer", name: "Security Printing Officer", grants: ["security_printing.jobs.view", "security_printing.jobs.create", "security_printing.jobs.update", "security_printing.custody.view", "security_printing.custody.record"] },
  { code: "secure_machine_operator", name: "Secure Machine Operator", grants: ["security_printing.jobs.view", "security_printing.jobs.update", "security_printing.custody.record", "production.work_orders.view", "production.outputs.create", "qr.scan.*"] },
  { code: "secure_materials_controller", name: "Secure Materials Controller", grants: ["security_printing.jobs.view", "security_printing.jobs.issue_materials", "security_printing.custody.record", "inventory.stock.view"] },
  { code: "secure_stock_controller", name: "Secure Stock Controller", grants: ["security_printing.batches.*", "security_printing.jobs.view", "inventory.stock.view", "qr.codes.view", "qr.labels.create"] },
  { code: "spoilage_controller", name: "Spoilage Controller", grants: ["security_printing.jobs.view", "security_printing.jobs.update", "security_printing.batches.*", "quality.defects.*", "quality.ncrs.view"] },
  { code: "security_printing_auditor", name: "Security Printing Auditor", grants: ["security_printing.audit.*", "security_printing.custody.view", "security_printing.jobs.view", "admin.audit.view", "reports.security.view"] },
  { code: "secure_job_approver", name: "Secure Job Approver", grants: ["security_printing.jobs.view", "security_printing.jobs.approve", "security_printing.jobs.reject", "security_printing.jobs.authorize_materials", "security_printing.jobs.reconcile", "workflows.instances.view", "workflows.instances.approve", "workflows.instances.reject", "workflows.instances.return", "dashboard.*", "reports.executive.view", "notifications.notifications.*"] },
  // HR
  { code: "hr_manager", name: "HR Manager", grants: ["hr.*", "workflows.instances.*", "communication.command.view", "communication.notifications.*", "communication.delivery_logs.view", "communication.announcements.view", "hikvision.*","governance.*","compliance.processing_activities.view","compliance.processing_activities.create","compliance.processing_activities.update","compliance.consents.view","compliance.consents.create","compliance.consents.withdraw","compliance.subject_requests.view","compliance.subject_requests.create","compliance.subject_requests.update","compliance.subject_requests.fulfil","compliance.subject_requests.refuse"] },
  { code: "hr_officer", name: "HR Officer", grants: ["hr.employees.*", "hr.contracts.*", "hr.certificates.*", "hr.legal_rules.view", "hr.attendance.*", "hr.leave.*", "hr.loans.*", "hr.divisions.*", "hr.locations.*", "hr.org_units.*", "hr.teams.*", "hr.job_families.*", "hr.job_grades.*", "hr.positions.*", "hr.position_assignments.*", "hr.workforce_plans.*", "hr.shifts.*", "hr.shift_assignments.*", "hr.timesheets.*", "hr.overtime.*", "hr.leave_types.*", "hr.leave_policies.*", "hr.leave_accruals.*", "hr.leave_balances.*", "hr.holidays.*", "hr.benefit_plans.*", "hr.benefit_enrollments.*", "hr.benefit_claims.*", "hr.grievances.*", "hr.investigations.*", "hr.disciplinary.*", "hr.warnings.*", "hr.asset_assignments.*", "hr.employee_requests.*", "hr.projects.*", "hr.onboarding.*", "hr.offboardings.*", "hr.alumni.view", "hr.payroll_components.view", "hr.employee_salaries.view", "hr.employee_earnings.view", "hr.employee_deductions.view", "hr.employee_benefits.view", "hr.overtime_records.view", "hr.bonus_records.view", "hr.commission_records.view", "hr.final_settlements.view", "hr.final_settlements.create", "hr.final_settlements.update", "hr.final_settlements.submit", "hikvision.command.view", "hikvision.dashboard.view", "hikvision.devices.view", "hikvision.events.view", "hikvision.exceptions.view", "hikvision.exceptions.assign", "hikvision.exceptions.resolve", "hikvision.sync.view", "hikvision.configuration.view", "hikvision.health.view", "hikvision.reports.view", "hikvision.employee_links.view","governance.delegations.view","governance.signature_profiles.view","governance.document_signatures.view","compliance.processing_activities.view","compliance.processing_activities.create","compliance.processing_activities.update","compliance.consents.view","compliance.consents.create","compliance.consents.withdraw","compliance.subject_requests.view","compliance.subject_requests.create","compliance.subject_requests.update","compliance.subject_requests.fulfil","compliance.subject_requests.refuse"] },
  { code: "hr_assistant", name: "HR Assistant", grants: ["hr.employees.view", "hr.employees.create", "hr.attendance.*", "hr.leave.view", "hr.positions.view", "hr.onboarding.*", "hr.offboardings.view", "hr.alumni.view", "hr.employee_requests.*", "hr.leave_types.view", "hr.holidays.view", "hr.asset_assignments.view", "hr.employee_identity.view", "hr.employee_card.view", "hr.employee_qr.view", "hr.employee_assignments.view", "hikvision.dashboard.view", "hikvision.devices.view", "hikvision.events.view", "hikvision.exceptions.view", "hikvision.health.view", "hikvision.sync.view"] },
  { code: "recruitment_officer", name: "Recruitment Officer", grants: ["hr.requisitions.*", "hr.vacancies.*", "hr.vacancy_channels.*", "hr.candidates.*", "hr.applications.*", "hr.interviews.*", "hr.assessments.*", "hr.offers.*", "hr.onboarding.view", "hr.positions.view", "hr.workforce_plans.view", "hr.employees.view"] },
  { code: "training_officer", name: "Training Officer", grants: ["hr.training_catalog.*", "hr.training_sessions.*", "hr.training_requests.*", "hr.training_enrollments.*", "hr.training_certificates.*", "hr.competencies.*", "hr.employees.view"] },
  { code: "performance_officer", name: "Performance Officer", grants: ["hr.performance_goals.*", "hr.performance_kpis.*", "hr.performance_reviews.*", "hr.pips.*", "hr.employees.view"] },
  { code: "payroll_manager", name: "Payroll Manager", grants: ["hr.payrolls.view", "hr.payrolls.update", "hr.payrolls.submit", "hr.payrolls.approve", "hr.payrolls.post", "hr.payrolls.print", "hr.payroll_components.*", "hr.employee_salaries.*", "hr.employee_earnings.*", "hr.employee_deductions.*", "hr.employee_benefits.*", "hr.overtime_records.*", "hr.bonus_records.*", "hr.commission_records.*", "hr.statutory_configs.view", "hr.payroll_settings.*", "hr.employees.view", "hr.loans.view", "hr.timesheets.view", "hr.overtime.view", "hr.employee_requests.view", "hr.final_settlements.*", "hr.loans.approve", "hr.loans.write_off", "hr.advances.view", "hr.advances.approve", "workflows.instances.*"] },
  { code: "payroll_officer", name: "Payroll Officer", grants: ["hr.payrolls.view", "hr.payrolls.create", "hr.payrolls.update", "hr.payrolls.submit", "hr.payrolls.print", "hr.payroll_components.view", "hr.employee_salaries.view", "hr.employee_salaries.create", "hr.employee_salaries.update", "hr.employee_earnings.view", "hr.employee_earnings.create", "hr.employee_earnings.update", "hr.employee_deductions.view", "hr.employee_deductions.create", "hr.employee_deductions.update", "hr.employee_benefits.view", "hr.employee_benefits.create", "hr.employee_benefits.update", "hr.overtime_records.view", "hr.overtime_records.create", "hr.overtime_records.update", "hr.bonus_records.view", "hr.bonus_records.create", "hr.bonus_records.update", "hr.commission_records.view", "hr.commission_records.create", "hr.commission_records.update", "hr.statutory_configs.view", "hr.payroll_settings.view", "hr.timesheets.view", "hr.overtime.view", "hr.employees.view", "hr.final_settlements.view", "hr.final_settlements.create", "hr.final_settlements.update", "hr.final_settlements.submit", "hr.final_settlements.export"] },
  { code: "time_attendance_officer", name: "Time & Attendance Officer", grants: ["hr.attendance.*", "hr.shifts.*", "hr.shift_assignments.*", "hr.timesheets.*", "hr.overtime.*", "hr.holidays.view", "hr.employees.view", "hr.leave.view", "hikvision.*"] },
  { code: "employee_self_service", name: "Employee Self-Service User", grants: ["hr.leave.view", "hr.leave.create", "hr.attendance.view", "hr.payslips.view", "hr.employee_requests.*", "hr.benefit_plans.view", "hr.benefit_enrollments.view", "hr.training_catalog.view", "hr.training_sessions.view", "hr.competencies.view", "hr.performance_goals.view", "hr.performance_reviews.view", "hr.holidays.view", "hr.contracts.view", "hr.contracts.sign", "hr.contracts.download", "hr.certificates.view", "notifications.notifications.*", "hr.attendance.view_own","governance.signature_profiles.view","governance.signature_profiles.create","governance.signature_profiles.submit","governance.signature_profiles.upload","governance.document_signatures.verify"] },
  { code: "onboarding_officer", name: "Onboarding Officer", grants: ["hr.onboarding.*", "hr.employees.view", "hr.asset_assignments.*", "hr.positions.view", "hr.employee_requests.view"] },
  { code: "benefits_officer", name: "Benefits Officer", grants: ["hr.benefit_plans.*", "hr.benefit_enrollments.*", "hr.benefit_claims.*", "hr.employee_benefits.*", "hr.employees.view"] },
  { code: "workforce_planner", name: "Workforce Planner", grants: ["hr.workforce_plans.*", "hr.workforce_scenarios.*", "hr.positions.view", "hr.job_families.view", "hr.job_grades.view", "hr.employees.view"] },
  { code: "relations_officer", name: "Employee Relations Officer", grants: ["hr.grievances.*", "hr.investigations.*", "hr.disciplinary.*", "hr.warnings.*", "hr.employees.view"] },
  // Logistics
  { code: "logistics_manager", name: "Logistics Manager", grants: ["logistics.*", "sales.delivery_notes.*", "reports.*"] },
  { code: "logistics_officer", name: "Logistics Officer", grants: ["logistics.trips.*", "logistics.fuel.*", "logistics.fleet.*", "logistics.deliveries.*"] },
  { code: "dispatch_manager", name: "Dispatch Manager", grants: ["sales.delivery_notes.*", "logistics.deliveries.*", "inventory.stock.view", "qr.scan.*"] },
  { code: "fleet_manager", name: "Fleet Manager", grants: ["logistics.vehicles.*", "logistics.fuel.*", "logistics.fleet.*", "logistics.drivers.*", "logistics.routes.*"] },
  { code: "fleet_officer", name: "Fleet Officer", grants: ["logistics.vehicles.view", "logistics.vehicles.update", "logistics.fuel.*", "logistics.fleet.*"] },
  { code: "delivery_coordinator", name: "Delivery Coordinator", grants: ["logistics.deliveries.*", "logistics.trips.view", "sales.delivery_notes.view"] },
  { code: "driver", name: "Driver", grants: ["logistics.trips.view", "logistics.trips.update", "logistics.deliveries.view", "logistics.deliveries.deliver", "qr.scan.*", "sales.delivery_notes.view"] },
  // Assets
  { code: "asset_manager", name: "Asset Manager", grants: ["assets.*", "finance.journals.view", "finance.journals.create", "finance.journals.post", "admin.audit.view"] },
  { code: "asset_officer", name: "Asset Officer", grants: ["assets.register.*", "assets.tags.*", "assets.transfers.*", "assets.movements.*", "assets.assignments.*", "assets.locations.*", "assets.categories.*", "assets.types.*", "assets.classes.*", "assets.maintenance.*", "assets.warranties.*", "assets.insurance.*", "assets.documents.*", "assets.photos.*", "assets.depreciation.*", "assets.scans.*", "assets.timeline.*", "assets.dashboards.*", "assets.reports.*", "assets.imports.*", "assets.exports.*"] },
  { code: "asset_custodian", name: "Asset Custodian", grants: ["assets.register.view", "assets.register.print", "assets.register.scan", "assets.register.verify", "assets.register.comment", "assets.tags.view", "assets.scans.*", "assets.timeline.*", "assets.dashboards.view", "assets.documents.view", "assets.photos.view", "qr.scan.*"] },
  { code: "asset_auditor", name: "Asset Auditor", grants: ["assets.register.view", "assets.register.audit", "assets.register.verify", "assets.register.scan", "assets.audits.*", "assets.audit_items.*", "assets.anomalies.*", "assets.movements.view", "assets.scans.*", "assets.timeline.*", "assets.dashboards.view", "assets.reports.view", "admin.audit.view"] },
  { code: "asset_storekeeper", name: "Asset Storekeeper", grants: ["assets.register.view", "assets.register.scan", "assets.register.verify", "assets.register.checkin", "assets.register.checkout", "assets.register.comment", "assets.tags.view", "assets.tags.print", "assets.locations.view", "assets.scans.*", "assets.timeline.*", "assets.dashboards.view", "qr.scan.*"] },
  { code: "asset_finance", name: "Asset Finance Officer", grants: ["assets.register.view", "assets.register.capitalize", "assets.register.depreciate", "assets.register.impair", "assets.depreciation.*", "assets.impairments.*", "assets.disposals.*", "assets.reports.*", "assets.exports.*", "finance.journals.view", "finance.journals.post"] },
  // Analytics
  { code: "bi_manager", name: "BI Manager", grants: ["reports.*", "admin.exports.*", "admin.imports.*"] },
  { code: "data_analyst", name: "Data Analyst", grants: ["reports.*", "admin.exports.*"] },
  { code: "reporting_officer", name: "Reporting Officer", grants: ["reports.view", "reports.sales.view", "reports.procurement.view", "reports.inventory.view", "reports.production.view", "reports.finance.view", "reports.export", "reports.builder.view", "reports.builder.run", "reports.kpis.view"] },
  { code: "executive_viewer", name: "Executive Viewer", grants: ["reports.dashboards.view", "reports.dashboards.create", "reports.executive.view", "dashboard.*"] },
  { code: "department_analyst", name: "Department Analyst", grants: ["reports.view", "reports.export", "reports.builder.view", "reports.builder.run", "reports.kpis.view"] },
  // Healthcare
  { code: "healthcare_admin", name: "Healthcare Administrator", grants: ["healthcare.*", "inventory.stock.view", "reports.healthcare.*", "admin.audit.view"] },
  { code: "doctor", name: "Doctor", grants: ["healthcare.patients.*", "healthcare.visits.*", "healthcare.appointments.*", "healthcare.emrs.*", "healthcare.diagnoses.*", "healthcare.vitals.*", "healthcare.observations.*", "healthcare.prescriptions.*", "healthcare.lab_requests.*", "healthcare.lab_results.view", "healthcare.practitioners.view", "qr.scan.*", "reports.healthcare.view", "notifications.notifications.*"] },
  { code: "nurse", name: "Nurse", grants: ["healthcare.patients.view", "healthcare.patients.create", "healthcare.patients.update", "healthcare.visits.*", "healthcare.appointments.*", "healthcare.vitals.*", "healthcare.observations.*", "healthcare.prescriptions.view", "healthcare.lab_requests.create", "healthcare.beds.view", "healthcare.wards.view", "qr.scan.*"] },
  { code: "pharmacist", name: "Pharmacist", grants: ["healthcare.prescriptions.*", "healthcare.dispensings.*", "inventory.stock.view", "inventory.items.view", "inventory.batches.view", "inventory.movements.view", "qr.scan.*", "reports.healthcare.view"] },
  { code: "lab_technician", name: "Lab Technician", grants: ["healthcare.lab_requests.*", "healthcare.lab_results.*", "healthcare.patients.view", "inventory.items.view", "inventory.stock.view", "qr.scan.*"] },
  { code: "receptionist", name: "Receptionist", grants: ["healthcare.patients.*", "healthcare.visits.create", "healthcare.visits.update", "healthcare.visits.view", "healthcare.appointments.*", "healthcare.bills.view", "crm.customers.view", "qr.scan.*", "notifications.notifications.*"] },
  { code: "insurance_officer", name: "Insurance Officer", grants: ["healthcare.insurance_payers.*", "healthcare.insurance_claims.*", "healthcare.bills.view", "healthcare.patients.view", "healthcare.visits.view", "reports.healthcare.view"] },
  { code: "medical_auditor", name: "Medical Auditor", grants: ["healthcare.patients.view", "healthcare.visits.view", "healthcare.emrs.view", "healthcare.prescriptions.view", "healthcare.dispensings.view", "healthcare.lab_requests.view", "healthcare.lab_results.view", "healthcare.insurance_claims.view", "healthcare.bills.view", "admin.audit.view", "reports.healthcare.view"] },
  { code: "ward_nurse", name: "Ward Nurse", grants: ["healthcare.beds.view", "healthcare.beds.assign", "healthcare.beds.release", "healthcare.visits.view", "healthcare.visits.admit", "healthcare.visits.discharge", "healthcare.vitals.*", "healthcare.observations.*", "healthcare.patients.view", "qr.scan.*"] },
  // ---------------------------------------------------------------
  // Service Desk & ITSM
  // ---------------------------------------------------------------
  { code: "service_desk_agent", name: "Service Desk Agent", grants: [
    "service_desk.command.view",
    "service_desk.tickets.view","service_desk.tickets.create","service_desk.tickets.update",
    "service_desk.tickets.reply","service_desk.tickets.assign","service_desk.tickets.resolve",
    "service_desk.tickets.close","service_desk.tickets.reopen","service_desk.tickets.escalate",
    "service_desk.tickets.print","service_desk.tickets.verify","service_desk.tickets.export","service_desk.tickets.create_on_behalf",
    "service_desk.internal_notes.view","service_desk.internal_notes.create",
    "service_desk.queues.view","service_desk.teams.view","service_desk.categories.view",
    "service_desk.assets.view","service_desk.asset_scans.view","service_desk.asset_scans.scan","service_desk.asset_scans.report",
    "service_desk.knowledge.view","service_desk.knowledge.create","service_desk.knowledge.update","service_desk.knowledge.rate",
    "service_desk.service_requests.view","service_desk.service_requests.update",
    "service_desk.incidents.view","service_desk.incidents.update",
    "service_desk.problems.view","service_desk.known_errors.view",
    "service_desk.changes.view","service_desk.access_requests.view",
    "service_desk.escalations.view",
    "service_desk.dashboards.agent","service_desk.reports.view",
  ] },
  { code: "service_desk_technician", name: "Service Desk Technician", grants: [
    "service_desk.command.view",
    "service_desk.tickets.view","service_desk.tickets.create","service_desk.tickets.update",
    "service_desk.tickets.reply","service_desk.tickets.assign","service_desk.tickets.resolve",
    "service_desk.tickets.close","service_desk.tickets.reopen","service_desk.tickets.escalate","service_desk.tickets.print","service_desk.tickets.create_on_behalf",
    "service_desk.internal_notes.view","service_desk.internal_notes.create",
    "service_desk.queues.view","service_desk.teams.view","service_desk.skills.view","service_desk.categories.view",
    "service_desk.assets.view","service_desk.asset_scans.view","service_desk.asset_scans.scan","service_desk.asset_scans.report",
    "service_desk.knowledge.view","service_desk.knowledge.create","service_desk.knowledge.update","service_desk.knowledge.rate",
    "service_desk.service_requests.view","service_desk.service_requests.update","service_desk.service_requests.fulfil",
    "service_desk.incidents.view","service_desk.incidents.update","service_desk.incidents.resolve",
    "service_desk.problems.view","service_desk.problems.update","service_desk.problems.investigate",
    "service_desk.known_errors.view","service_desk.known_errors.create",
    "service_desk.changes.view","service_desk.changes.update","service_desk.changes.implement",
    "service_desk.access_requests.view",
    "service_desk.escalations.view",
    "service_desk.dashboards.agent","service_desk.reports.view",
  ] },
  { code: "service_desk_manager", name: "Service Desk Manager", grants: [
    "service_desk.command.view","service_desk.tickets.*","service_desk.internal_notes.*",
    "service_desk.queues.*","service_desk.teams.*","service_desk.skills.*","service_desk.categories.*",
    "service_desk.sla.*","service_desk.escalations.*",
    "service_desk.service_requests.*","service_desk.incidents.*",
    "service_desk.problems.*","service_desk.known_errors.*",
    "service_desk.changes.*","service_desk.change_approvals.*","service_desk.access_requests.*",
    "service_desk.knowledge.*",
    "service_desk.assets.view","service_desk.asset_scans.*",
    "service_desk.dashboards.*","service_desk.reports.*","service_desk.settings.*",
    "service_desk.audit.view","service_desk.admin",
  ] },
  // Executive and operational structure (org chart, migration 0167 section 1).
  { code: "operations_manager", name: "Operations Manager", grants: [
    "workflows.instances.*",
    "production.*","quality.*","maintenance.*","inventory.*",
    "procurement.*","expenditure.*","logistics.*","reports.*",
    "communication.*","documents.*","dashboard.*","notifications.*",
    "service_desk.*","hr.attendance.*",
    "organisation.manufacturing.manage","organisation.inventory.manage",
    "organisation.structure.manage","organisation.audit.view",
    "organisation.settings.view",
    "governance.delegations.view","governance.acting_roles.view",
    "governance.document_signatures.view","governance.document_signatures.create",
    "governance.document_signatures.verify","governance.signature_profiles.view",
    "governance.signature_authority_scopes.view",
  ] },
  { code: "md_assistant", name: "Managing Director Assistant", grants: [
    "dashboard.*","notifications.*","documents.*","communication.*",
    "service_desk.*","workflows.instances.view",
    "reports.executive.*","reports.dashboards.*","reports.kpis.*",
    "organisation.settings.view","organisation.audit.view",
    "organisation.documents.manage",
    "governance.delegations.view","governance.acting_roles.view",
    "governance.document_signatures.view","governance.signature_profiles.view",
    "governance.signature_authority_scopes.view",
  ] },
  { code: "operations_assistant", name: "Operations Assistant", grants: [
    "dashboard.*","notifications.*","documents.*","communication.*",
    "service_desk.*","workflows.instances.view",
    "reports.dashboards.*","reports.kpis.*","reports.operations.*",
    "inventory.*.view","production.*.view","procurement.*.view",
    "expenditure.*.view","logistics.*.view","quality.*.view",
  ] },
  { code: "office_attendant", name: "Office Attendant", grants: [
    "dashboard.*","notifications.*",
    "documents.documents.view","documents.library.view",
    "communication.announcements.view","communication.messages.view",
    "communication.messages.create",
    "service_desk.tickets.view","service_desk.tickets.create",
  ] },
];

// ---------------------------------------------------------------------------
// Service Desk grants for roles defined above.
// Declared centrally (rather than appending to the long inline grant lists)
// so Service Desk capability for existing personas stays auditable in one place.
// ---------------------------------------------------------------------------
const SERVICE_DESK_ROLE_EXTENSIONS = {
  system_administrator: ["service_desk.*"],
  it_support_administrator: ["service_desk.*"],
  security_administrator: [
    "service_desk.command.view","service_desk.tickets.view","service_desk.tickets.escalate",
    "service_desk.internal_notes.view","service_desk.incidents.*","service_desk.asset_scans.view","service_desk.tickets.create_on_behalf",
    "service_desk.audit.view","service_desk.dashboards.manager",
  ],
  operations_director: [
    "service_desk.command.view","service_desk.tickets.view","service_desk.tickets.escalate",
    "service_desk.internal_notes.view","service_desk.incidents.*","service_desk.problems.view",
    "service_desk.changes.view","service_desk.escalations.view","service_desk.asset_scans.view","service_desk.tickets.create_on_behalf",
    "service_desk.dashboards.*","service_desk.reports.*",
  ],
  hr_manager: ["service_desk.command.view","service_desk.tickets.view_own","service_desk.tickets.create","service_desk.tickets.reply"],
  employee_self_service: [
    "service_desk.command.view",
    "service_desk.tickets.view_own","service_desk.tickets.create","service_desk.tickets.reply",
    "service_desk.tickets.close_own","service_desk.tickets.verify",
    "service_desk.knowledge.view","service_desk.knowledge.rate",
    "service_desk.asset_scans.view","service_desk.asset_scans.scan",
    "service_desk.access_requests.view_own","service_desk.access_requests.create",
    "service_desk.dashboards.employee",
  ],
};
// ---------------------------------------------------------------------------
// Organisation Settings grants (migration 0164).
// Mirrors the explicit role grants seeded by 0164 exactly: the same roles, the
// same codes, and deliberately no grant to procurement_manager - administrative
// access and business approval authority stay separate (spec section 26).
// ---------------------------------------------------------------------------
const ORGANISATION_PERMISSIONS = {
  view: "organisation.settings.view",
  create: "organisation.settings.create",
  update: "organisation.settings.update",
  remove: "organisation.settings.delete",
  structure: "organisation.structure.manage",
  tax: "organisation.tax.manage",
  finance: "organisation.finance.manage",
  payroll: "organisation.payroll.manage",
  documents: "organisation.documents.manage",
  security: "organisation.security.manage",
  integrations: "organisation.integrations.manage",
  qr: "organisation.qr.manage",
  manufacturing: "organisation.manufacturing.manage",
  inventory: "organisation.inventory.manage",
  hr: "organisation.hr.manage",
  attendance: "organisation.attendance.manage",
  audit: "organisation.audit.view",
};
const OPERM = ORGANISATION_PERMISSIONS;
const ORGANISATION_ROLE_EXTENSIONS = {
  super_administrator: Object.values(OPERM),
  system_administrator: [OPERM.view, OPERM.update, OPERM.structure, OPERM.documents, OPERM.security, OPERM.integrations, OPERM.audit],
  security_administrator: [OPERM.view, OPERM.security, OPERM.audit],
  integration_administrator: [OPERM.view, OPERM.integrations],
  audit_administrator: [OPERM.view, OPERM.audit],
  data_protection_officer: [OPERM.view, OPERM.audit],
  backup_administrator: [OPERM.view, OPERM.audit],
  cfo: [OPERM.view, OPERM.finance, OPERM.tax, OPERM.audit],
  finance_manager: [OPERM.view, OPERM.finance, OPERM.tax, OPERM.audit],
  chief_accountant: [OPERM.view, OPERM.finance, OPERM.tax, OPERM.audit],
  financial_controller: [OPERM.view, OPERM.finance, OPERM.tax, OPERM.audit],
  tax_officer: [OPERM.view, OPERM.tax],
  payroll_manager: [OPERM.view, OPERM.payroll],
  payroll_accountant: [OPERM.view, OPERM.payroll],
  hr_director: [OPERM.view, OPERM.hr, OPERM.attendance],
  hr_manager: [OPERM.view, OPERM.hr, OPERM.attendance],
  production_director: [OPERM.view, OPERM.manufacturing, OPERM.inventory],
  production_manager: [OPERM.view, OPERM.manufacturing, OPERM.inventory],
  quality_manager: [OPERM.view, OPERM.manufacturing, OPERM.inventory],
  security_printing_director: [OPERM.view, OPERM.manufacturing, OPERM.inventory],
  warehouse_manager: [OPERM.view, OPERM.inventory],
  inventory_controller: [OPERM.view, OPERM.inventory],
  supply_chain_manager: [OPERM.view, OPERM.inventory],
  security_printing_manager: [OPERM.view, OPERM.qr],
  secure_stock_controller: [OPERM.view, OPERM.qr],
  service_desk_manager: [OPERM.view, OPERM.documents],
};

// ---------------------------------------------------------------------------
// Workflow decision grants (migration 0167 section 2).
// Every role that appears on a workflow step has to be able to decide one:
// decideTask authorises through role_permissions, not through the roles.permissions
// cache, so a step assigned to a role without this module silently deadlocks.
// Declared centrally for the same reason as the Service Desk grants above.
// ---------------------------------------------------------------------------
const WORKFLOW_INSTANCE_ROLE_EXTENSIONS = {
  accountant: ["workflows.instances.*"],
  asset_manager: ["workflows.instances.*"],
  production_supervisor: ["workflows.instances.*"],
  quality_inspector: ["workflows.instances.*"],
  warehouse_manager: ["workflows.instances.*"],
  procurement_manager: ["workflows.instances.*"],
  finance_manager: ["workflows.instances.*"],
  cfo: ["workflows.instances.*"],
  chief_accountant: ["workflows.instances.*"],
  hr_manager: ["workflows.instances.*"],
  payroll_manager: ["workflows.instances.*"],
  sales_manager: ["workflows.instances.*"],
  secure_job_approver: ["workflows.instances.*"],
  operations_manager: ["workflows.instances.*"],
};

// ---------------------------------------------------------------------------
// Company Mailing System (migration 0169) role grants.
//
// The `communication` module gained 17 mail sub-resources (see MODULES above).
// Roles holding a broad `communication.*` grant pick those up automatically
// through expandGrants(); every other role that legitimately works with mail is
// enumerated here, because reconcileRbac() rebuilds role_permissions from
// ROLES[].grants on every reseed and therefore wipes any INSERT a migration
// performs.
//
// Tiers are additive and declared once so the intent of each tier stays
// reviewable rather than diffused across 100+ hand-written arrays. Note that
// these deliberately do NOT grant `communication.settings.manage` or the
// broader messaging/announcement resources: mail capability must not silently
// widen into transport-credential control.
// ---------------------------------------------------------------------------
const MAIL_VIEW = [
  "communication.mailboxes.view",
  "communication.mail_contacts.view",
  "communication.mail_classifications.view",
  "communication.mail_attachments.view",
];
const MAIL_COMPOSE = [
  ...MAIL_VIEW,
  "communication.emails.view",
  "communication.mail_drafts.*",
  "communication.mail_labels.*",
  "communication.mail_scheduled.view",
  "communication.mail_scheduled.create",
  "communication.mail_attachments.upload",
  "communication.mail_signatures.view",
  "communication.mail_signatures.create",
  "communication.mail_signatures.update",
];
const MAIL_SEND = [
  ...MAIL_COMPOSE,
  "communication.emails.send",
  "communication.mail_attachments.download",
  "communication.mail_approvals.view",
  "communication.mail_approvals.submit",
  "communication.mail_distribution_lists.view",
  "communication.mail_scheduler.view",
];
const MAIL_MANAGE = [
  ...MAIL_SEND,
  "communication.emails.manage",
  "communication.mailboxes.create",
  "communication.mailboxes.update",
  "communication.mailboxes.manage",
  "communication.mailbox_members.*",
  "communication.mailbox_delegations.*",
  "communication.mail_approvals.approve",
  "communication.mail_approvals.reject",
  "communication.mail_approvals.manage",
  "communication.mail_distribution_lists.create",
  "communication.mail_distribution_lists.update",
  "communication.mail_distribution_lists.manage",
  "communication.mail_rules.*",
  "communication.mail_signatures.manage",
  "communication.mail_classifications.manage",
  "communication.mail_audit.view",
  "communication.mail_admin.view",
  "communication.mail_scheduler.manage",
];
const MAIL_ADMIN = [
  ...MAIL_MANAGE,
  "communication.mail_providers.*",
  "communication.mail_admin.manage",
  "communication.mail_audit.export",
  "communication.mail_contacts.export",
  "communication.mail_attachments.delete",
];

const MAIL_ROLE_EXTENSIONS = {
  // --- Platform, security and compliance governance of the mail subsystem ---
  security_administrator: MAIL_ADMIN,
  it_support_administrator: MAIL_ADMIN,
  integration_administrator: MAIL_ADMIN,
  audit_administrator: MAIL_ADMIN,
  data_protection_officer: MAIL_ADMIN,
  backup_administrator: MAIL_ADMIN,

  // --- Directors, functional heads and approvers: departmental mailbox control ---
  operations_director: MAIL_MANAGE,
  cfo: MAIL_MANAGE,
  finance_manager: MAIL_MANAGE,
  chief_accountant: MAIL_MANAGE,
  financial_controller: MAIL_MANAGE,
  internal_auditor: MAIL_MANAGE,
  hr_manager: MAIL_MANAGE,
  sales_director: MAIL_MANAGE,
  sales_manager: MAIL_MANAGE,
  crm_manager: MAIL_MANAGE,
  procurement_director: MAIL_MANAGE,
  procurement_manager: MAIL_MANAGE,
  supply_chain_manager: MAIL_MANAGE,
  warehouse_manager: MAIL_MANAGE,
  production_director: MAIL_MANAGE,
  production_manager: MAIL_MANAGE,
  quality_director: MAIL_MANAGE,
  quality_manager: MAIL_MANAGE,
  security_printing_director: MAIL_MANAGE,
  security_printing_manager: MAIL_MANAGE,
  logistics_manager: MAIL_MANAGE,
  asset_manager: MAIL_MANAGE,
  service_desk_manager: MAIL_MANAGE,
  bi_manager: MAIL_MANAGE,
  payroll_manager: MAIL_MANAGE,
  maintenance_manager: MAIL_MANAGE,

  // --- Officers, executives and analysts: full compose/send/receive ---
  accountant: MAIL_SEND,
  ar_officer: MAIL_SEND,
  ap_officer: MAIL_SEND,
  cashier: MAIL_SEND,
  treasury_officer: MAIL_SEND,
  budget_officer: MAIL_SEND,
  tax_officer: MAIL_SEND,
  payroll_accountant: MAIL_SEND,
  sales_executive: MAIL_SEND,
  sales_representative: MAIL_SEND,
  crm_officer: MAIL_SEND,
  account_manager: MAIL_SEND,
  customer_service_officer: MAIL_SEND,
  sales_coordinator: MAIL_SEND,
  procurement_officer: MAIL_SEND,
  purchasing_officer: MAIL_SEND,
  procurement_assistant: MAIL_SEND,
  supplier_relationship_manager: MAIL_SEND,
  procurement_evaluator: MAIL_SEND,
  procurement_approver: MAIL_SEND,
  warehouse_supervisor: MAIL_SEND,
  storekeeper: MAIL_SEND,
  inventory_controller: MAIL_SEND,
  inventory_officer: MAIL_SEND,
  receiving_officer: MAIL_SEND,
  dispatch_officer: MAIL_SEND,
  dispatch_manager: MAIL_SEND,
  logistics_officer: MAIL_SEND,
  fleet_manager: MAIL_SEND,
  fleet_officer: MAIL_SEND,
  delivery_coordinator: MAIL_SEND,
  production_planner: MAIL_SEND,
  production_scheduler: MAIL_SEND,
  production_supervisor: MAIL_SEND,
  production_officer: MAIL_SEND,
  work_order_manager: MAIL_SEND,
  production_cost_analyst: MAIL_SEND,
  maintenance_supervisor: MAIL_SEND,
  maintenance_planner: MAIL_SEND,
  maintenance_technician: MAIL_SEND,
  electrical_technician: MAIL_SEND,
  mechanical_technician: MAIL_SEND,
  machine_controller: MAIL_SEND,
  quality_supervisor: MAIL_SEND,
  quality_inspector: MAIL_SEND,
  qc_officer: MAIL_SEND,
  ncr_officer: MAIL_SEND,
  qa_auditor: MAIL_SEND,
  security_production_supervisor: MAIL_SEND,
  security_printing_officer: MAIL_SEND,
  security_printing_auditor: MAIL_SEND,
  secure_materials_controller: MAIL_SEND,
  secure_stock_controller: MAIL_SEND,
  secure_job_approver: MAIL_SEND,
  spoilage_controller: MAIL_SEND,
  hr_officer: MAIL_SEND,
  hr_assistant: MAIL_SEND,
  recruitment_officer: MAIL_SEND,
  training_officer: MAIL_SEND,
  performance_officer: MAIL_SEND,
  payroll_officer: MAIL_SEND,
  time_attendance_officer: MAIL_SEND,
  onboarding_officer: MAIL_SEND,
  benefits_officer: MAIL_SEND,
  workforce_planner: MAIL_SEND,
  relations_officer: MAIL_SEND,
  asset_officer: MAIL_SEND,
  asset_custodian: MAIL_SEND,
  asset_auditor: MAIL_SEND,
  asset_storekeeper: MAIL_SEND,
  asset_finance: MAIL_SEND,
  data_analyst: MAIL_SEND,
  reporting_officer: MAIL_SEND,
  department_analyst: MAIL_SEND,
  executive_viewer: MAIL_SEND,
  service_desk_agent: MAIL_SEND,
  service_desk_technician: MAIL_SEND,
  receptionist: MAIL_SEND,
  healthcare_admin: MAIL_SEND,
  medical_auditor: MAIL_SEND,
  insurance_officer: MAIL_SEND,
  stock_auditor: MAIL_SEND,
  stock_counter: MAIL_SEND,

  // --- Read-only mail awareness for roles without a primary desk ---
  office_attendant: MAIL_VIEW,
  employee_self_service: MAIL_VIEW,
};

// ---------------------------------------------------------------------------
// Cron administration grants. The cron routes and the Communication -> Cron Jobs
// tab check `system.cron.view` / `system.cron.manage`. Declared centrally so the
// capability survives reconcileRbac re-seeds, which rebuild role_permissions from
// ROLES[].grants and would otherwise drop a migration-only INSERT.
// ---------------------------------------------------------------------------
const CRON_PERMISSIONS = ["system.cron.view", "system.cron.manage"];

const CRON_ROLE_EXTENSIONS = {
  super_administrator: CRON_PERMISSIONS,
  system_administrator: CRON_PERMISSIONS,
  managing_director: CRON_PERMISSIONS,
  executive_director: CRON_PERMISSIONS,
  general_manager: CRON_PERMISSIONS,
  operations_director: CRON_PERMISSIONS,
  production_director: CRON_PERMISSIONS,
};

for (const role of ROLES) {
  const extra = [
    ...(SERVICE_DESK_ROLE_EXTENSIONS[role.code] || []),
    ...(ORGANISATION_ROLE_EXTENSIONS[role.code] || []),
    ...(WORKFLOW_INSTANCE_ROLE_EXTENSIONS[role.code] || []),
    ...(MAIL_ROLE_EXTENSIONS[role.code] || []),
    ...(CRON_ROLE_EXTENSIONS[role.code] || []),
  ];
  if (extra.length) role.grants = [...role.grants, ...extra];
}

module.exports = { ACTIONS, MODULES, EXTRA_PERMISSIONS, CRON_ROLE_EXTENSIONS, buildPermissions, ROLES };
