// ============================================================
// Permission + role catalogue (Hope Design ERP)
// Permission codes: {module}.{resource}.{action}
// ============================================================

const ACTIONS = ["view","create","update","delete","submit","approve","reject","cancel","void","archive","restore","print","export","import","scan","transfer","assign","release","convert","verify","post","generate","complete","admit","discharge","dispense","settle","terminate","delete_draft","manage_templates","manage_clauses","manage_versions","manage_legal_rules","view_audit","validate","sign","download","renew","vary","issue","manage","dispose","audit","depreciate","impair","capitalize","maintain","inspect","checkin","checkout","replace","activate","investigate","resolve","comment","reprint","perform","close","return"];

const MODULES = {
  dashboard: { overview: ["view"], kpis: ["view"] },
  crm: {
    leads: ["view","create","update","delete","submit","convert","assign","export","import"],
    customers: ["view","create","update","delete","submit","approve","block","export","import"],
    contacts: ["view","create","update","delete"],
    opportunities: ["view","create","update","delete","win","lose","assign"],
    activities: ["view","create","update","delete","complete"],
    complaints: ["view","create","update","delete","resolve","escalate"],
  },
  sales: {
    quotations: ["view","create","update","delete","submit","approve","reject","convert","revise","print","export","import"],
    orders: ["view","create","update","delete","submit","approve","reject","cancel","allocate","dispatch","print","export","import"],
    delivery_notes: ["view","create","update","submit","dispatch","deliver","confirm","print","export"],
    invoices: ["view","create","update","submit","approve","post","void","print","export"],
    receipts: ["view","create","update","post","void","print","export"],
    credit_notes: ["view","create","update","submit","approve","post","void","print","export"],
    debit_notes: ["view","create","update","submit","approve","post","void","print","export"],
    returns: ["view","create","update","approve","inspect","complete","print","export"],
    statements: ["view","print","export"],
  },
  procurement: {
    suppliers: ["view","create","update","delete","submit","approve","block","evaluate","export","import"],
    requisitions: ["view","create","update","submit","approve","reject","convert"],
    rfqs: ["view","create","update","issue","evaluate","award"],
    quotations: ["view","create","update","evaluate","select"],
    orders: ["view","create","update","submit","approve","reject","cancel","close","print","export","import"],
    goods_receipts: ["view","create","update","submit","approve","inspect","print"],
    supplier_invoices: ["view","create","update","submit","approve","match","post","void"],
    payments: ["view","create","update","submit","approve","release","post","void"],
    returns: ["view","create","update","approve","complete"],
    contracts: ["view","create","update","approve","expire"],
  },
  inventory: {
    items: ["view","create","update","delete","adjust","transfer","scan","count","export","import"],
    stock: ["view","count","adjust","transfer","export","import"],
    movements: ["view","create","export"],
    reservations: ["view","create","release","cancel"],
    adjustments: ["view","create","update","submit","approve","reject","post","cancel"],
    transfers: ["view","create","update","submit","approve","reject","complete","cancel"],
    batches: ["view","create","update","block","release"],
    bins: ["view","create","update","delete"],
    warehouses: ["view","create","update","delete"],
    zones: ["view","create","update","delete"],
    racks: ["view","create","update","delete"],
    shelves: ["view","create","update","delete"],
    ledger: ["view","export"],
    transactions: ["view","create","submit","approve","post","reverse","cancel"],
    counts: ["view","create","update","enter","approve","post","cancel","schedule"],
    quality_holds: ["view","create","update","release","reject"],
    handling_units: ["view","create","update","break","consolidate","dispatch"],
    traceability: ["view","export"],
    forecasts: ["view","create","update","override"],
    valuations: ["view","create","export"],
    alerts: ["view","acknowledge","resolve"],
    item_attributes: ["view","create","update","delete"],
    allocations: ["view","create","release","cancel"],
    reorder_recommendations: ["view","approve","convert","dismiss"],
    recalls: ["view","create","update","quarantine","close","notify"],
    risk: ["view","recalculate"],
    putaway: ["view","execute","confirm"],
    receiving: ["view","create","execute","confirm"],
    picking: ["view","create","execute","confirm"],
    packing: ["view","create","execute","confirm"],
    dispatch: ["view","create","execute","confirm"],
  },
  production: {
    plans: ["view","create","update","submit","approve","reject","execute"],
    work_orders: ["view","create","update","delete","submit","approve","reject","release","start","complete","close","issue","return","record","print"],
    boms: ["view","create","update","delete","approve"],
    routings: ["view","create","update","delete","approve"],
    work_centres: ["view","create","update","delete"],
    machines: ["view","create","update","delete","operate","maintain","assign"],
    outputs: ["view","create","update"],
    downtime: ["view","create","update"],
    costing: ["view","recalculate"],
    kpis: ["view"],
    analytics: ["view","export"],
    command: ["view"],
    ai: ["view"],
    alerts: ["view","acknowledge","resolve"],
    schedule: ["view","create","update","publish"],
    traceability: ["view","export"],
    batches: ["view","create","update","close"],
    quality_holds: ["view","create","dispose","release"],
    rework: ["view","create","approve","complete"],
    subcontract: ["view","create","approve","receive","complete"],
    shifts: ["view","create","acknowledge"],
  },
  quality: {
    plans: ["view","create","update","delete","approve"],
    inspections: ["view","create","update","submit","approve","execute","quarantine"],
    results: ["view","create","update"],
    defects: ["view","create","update"],
    ncrs: ["view","create","update","investigate","close"],
    capa: ["view","create","update","verify","close"],
  },
  security_printing: {
    jobs: ["view","create","update","delete","submit","approve","reject","authorize_materials","issue_materials","reconcile","hold","resume","dispatch","print"],
    custody: ["view","record","witness"],
    batches: ["view","create","update"],
    operators: ["view","assign"],
    machines: ["view","assign"],
    audit: ["view"],
  },
  qr: {
    codes: ["view","create","generate","void","suspend","replace","archive"],
    labels: ["view","create","print","reprint"],
    scans: ["view","perform","verify"],
    templates: ["view","create","update","delete"],
    anomalies: ["view","investigate","resolve"],
    traceability: ["view","export"],
    recalls: ["view","create","update","close"],
    reams: ["view","create","generate","print"],
    cartons: ["view","create","seal","print"],
    packing: ["scan","seal"],
  },
  maintenance: {
    requests: ["view","create","update","assign","complete"],
    schedules: ["view","create","update","delete"],
    work_orders: ["view","create","update","complete"],
  },
  logistics: {
    vehicles: ["view","create","update","delete"],
    routes: ["view","create","update","delete"],
    drivers: ["view","create","update","delete"],
    trips: ["view","create","update","complete"],
    fuel: ["view","create","update"],
    fleet: ["view","create","update"],
    deliveries: ["view","create","update","dispatch","deliver","track"],
  },
  finance: {
    chart_of_accounts: ["view","create","update","delete"],
    journals: ["view","create","post","void","export","submit","approve","reject","reverse"],
    periods: ["view","create","open","close","lock"],
    banks: ["view","create","update","reconcile"],
    budgets: ["view","create","update","submit","approve","close"],
    expenses: ["view","create","update","submit","approve","post","void"],
    advances: ["view","create","settle","void"],
    taxes: ["view","create","update"],
    reports: ["view","print","export"],
    posting_rules: ["view","create","post"],
    templates: ["view","create"],
    tax_jurisdictions: ["view","create"],
    tax_rules: ["view","create"],
    tax_transactions: ["view","create"],
    efris: ["view","create","sync","cancel"],
    budget_revisions: ["view","create"],
    budget_commitments: ["view","create","release"],
    allocation_rules: ["view","create"],
    production_costs: ["view","create","post"],
    intercompany: ["view","create"],
    consolidation: ["view","run"],
    close_tasks: ["view","update"],
    audit: ["view"],
  },
  expenditure: {
    dashboards: ["view"],
    requisitions: ["view","create","update","submit","approve","fulfill","cancel"],
    expenses: ["view","create","update","submit","approve","post","void"],
    petty_cash: ["view","create","update","replenish","reconcile"],
    claims: ["view","create","approve","reimburse"],
    receipts: ["view","upload","verify"],
    payments: ["view","create","approve","post"],
    daily_close: ["view","create","approve"],
    reports: ["view"],
    settings: ["manage"],
  },
  hr: {
    employees: ["view","create","update","delete","terminate","export","import"],
    contracts: ["view","create","update","delete_draft","terminate","validate","submit","approve","reject","sign","download","export","renew","vary","generate","manage_templates","manage_clauses","manage_versions","manage_legal_rules","view_audit"],
    certificates: ["view","create","update","issue","download","export"],
    legal_rules: ["view","manage"],
    // Organization management
    divisions: ["view","create","update","delete"],
    locations: ["view","create","update","delete"],
    org_units: ["view","create","update","delete"],
    teams: ["view","create","update","delete"],
    job_families: ["view","create","update","delete"],
    job_grades: ["view","create","update","delete"],
    positions: ["view","create","update","delete","assign"],
    position_assignments: ["view","create","update","delete"],
    // Workforce planning
    workforce_plans: ["view","create","update","submit","approve","reject","delete"],
    workforce_scenarios: ["view","create","update","delete","simulate"],
    // Recruitment / ATS
    requisitions: ["view","create","update","submit","approve","reject","cancel","delete"],
    vacancies: ["view","create","update","publish","unpublish","close","cancel","delete"],
    vacancy_channels: ["view","create","update","delete"],
    candidates: ["view","create","update","delete","import","export"],
    applications: ["view","create","update","submit","shortlist","advance","withdraw","reject"],
    interviews: ["view","create","update","complete","cancel"],
    assessments: ["view","create","update","complete"],
    offers: ["view","create","update","send","accept","decline","withdraw","expire"],
    onboarding: ["view","create","update","start","complete","cancel","delete"],
    attendance: ["view","create","update","export"],
    shifts: ["view","create","update","delete","assign"],
    shift_assignments: ["view","create","update","delete"],
    timesheets: ["view","create","update","submit","approve","reject"],
    overtime: ["view","create","update","approve","reject"],
    leave: ["view","create","update","approve","reject"],
    leave_types: ["view","create","update","delete"],
    leave_policies: ["view","create","update","delete"],
    leave_accruals: ["view","create","update","accrue"],
    leave_balances: ["view","update"],
    holidays: ["view","create","update","delete"],
    // Performance
    performance_goals: ["view","create","update","delete","complete"],
    performance_kpis: ["view","create","update","delete"],
    performance_reviews: ["view","create","update","submit","approve","reject","complete"],
    pips: ["view","create","update","submit","approve","close"],
    // Learning & development
    training_catalog: ["view","create","update","delete"],
    training_sessions: ["view","create","update","delete","complete"],
    training_requests: ["view","create","update","submit","approve","reject"],
    training_enrollments: ["view","create","update","delete"],
    training_certificates: ["view","create","update","issue"],
    competencies: ["view","create","update","delete"],
    // Benefits
    benefit_plans: ["view","create","update","delete"],
    benefit_enrollments: ["view","create","update","delete","enroll"],
    benefit_claims: ["view","create","update","submit","approve","reject"],
    // Employee relations
    grievances: ["view","create","update","submit","investigate","resolve","close"],
    investigations: ["view","create","update","start","complete"],
    disciplinary: ["view","create","update","submit","investigate","decide","appeal","close"],
    warnings: ["view","create","update","issue","expire"],
    // HR asset assignments
    asset_assignments: ["view","create","update","return","delete"],
    // Employee identity / ID cards
    employee_assignments: ["view","create"],
    employee_identity: ["view","generate","replace","suspend"],
    employee_card: ["view","generate","issue","print","replace","suspend"],
    employee_qr: ["view","generate","scan","verify"],
    // Offboarding / alumni (exit lifecycle)
    offboardings: ["view","create","update","start","complete","cancel","waive","export"],
    alumni: ["view","export"],
    // Payroll configuration
    payroll_components: ["view","create","update","delete"],
    employee_salaries: ["view","create","update","delete"],
    employee_earnings: ["view","create","update","delete","submit","approve","reject"],
    employee_deductions: ["view","create","update","delete","submit","approve","reject"],
    employee_benefits: ["view","create","update","delete"],
    overtime_records: ["view","create","update","approve","reject"],
    bonus_records: ["view","create","update","approve","reject"],
    commission_records: ["view","create","update","approve","reject"],
    statutory_configs: ["view","create","update","delete","activate"],
    // Self-service
    employee_requests: ["view","create","update","cancel"],
    projects: ["view","create","update","delete"],
    // Legacy aliases kept for compatibility
    recruitment: ["view","create","update"],
    training: ["view","create","update"],
    performance: ["view","create","update"],
    payrolls: ["view","create","update","submit","approve","release","post","void","print"],
    payslips: ["view","print","send"],
    loans: ["view","create","update","approve","reject","pause","write_off"],
      advances: ["view","create","update","approve","reject"],
    final_settlements: ["view","create","update","submit","approve","reject","pay","export"],
  },
  healthcare: {
    facilities: ["view","create","update","delete","print","export","import"],
    wards: ["view","create","update","delete","assign"],
    beds: ["view","create","update","delete","assign","release"],
    practitioners: ["view","create","update","delete","assign","print","export","import"],
    patients: ["view","create","update","delete","admit","discharge","print","export","import","scan"],
    visits: ["view","create","update","delete","submit","admit","discharge","complete","print","export","import"],
    appointments: ["view","create","update","delete","submit","approve","reject","complete","print","export"],
    emrs: ["view","create","update","delete","complete","print","export","import"],
    diagnoses: ["view","create","update","delete"],
    vitals: ["view","create","update"],
    observations: ["view","create","update"],
    prescriptions: ["view","create","update","delete","submit","approve","reject","dispense","print","export"],
    dispensings: ["view","create","update","complete","print","export"],
    lab_requests: ["view","create","update","delete","submit","approve","complete","print","export"],
    lab_results: ["view","create","update","complete","print","export"],
    insurance_payers: ["view","create","update","delete","approve"],
    insurance_claims: ["view","create","update","submit","approve","reject","settle","print","export"],
    bills: ["view","create","update","submit","approve","post","print","export"],
  },
  assets: {
    register: ["view","create","update","delete","submit","approve","reject","dispose","transfer","audit","print","export","import","capitalize","depreciate","impair","assign","verify","scan","maintain","inspect","checkin","checkout","restore","archive","comment"],
    tags: ["view","create","generate","print","reprint","replace","void","archive"],
    transfers: ["view","create","update","submit","approve","reject","complete","cancel"],
    movements: ["view","create"],
    assignments: ["view","create","complete","return","cancel"],
    audits: ["view","create","update","submit","approve","close","cancel"],
    audit_items: ["view","create","update"],
    maintenance: ["view","create","update","submit","approve","complete","cancel"],
    disposals: ["view","create","update","submit","approve","reject","complete","cancel"],
    locations: ["view","create","update","delete"],
    categories: ["view","create","update","delete"],
    types: ["view","create","update","delete"],
    classes: ["view","create","update","delete"],
    warranties: ["view","create","update","delete"],
    insurance: ["view","create","update","delete"],
    documents: ["view","create","update","delete","download"],
    photos: ["view","create","delete"],
    depreciation: ["view","create","post"],
    impairments: ["view","create","submit","approve","reject","post"],
    scans: ["view","perform","verify"],
    anomalies: ["view","investigate","resolve"],
    custodians: ["view"],
    timeline: ["view"],
    dashboards: ["view"],
    reports: ["view","export"],
    imports: ["view","create"],
    exports: ["view","create"],
    settings: ["view","update"],
  },
  documents: {
    documents: ["view","create","update","delete","approve","archive","restore","download","sign"],
    versions: ["view","create"],
  },
  workflows: {
    workflows: ["view","create","update","delete","activate"],
    instances: ["view","approve","reject","return","delegate","escalate","cancel"],
  },
  notifications: { notifications: ["view","read"], tasks: ["view","create","update","complete"] },
  reports: {
    dashboards: ["view","create","update","delete"],
    executive: ["view"],
    sales: ["view","export"],
    procurement: ["view","export"],
    inventory: ["view","export"],
    production: ["view","export"],
    quality: ["view","export"],
    finance: ["view","export"],
    hr: ["view","export"],
    healthcare: ["view","export"],
    qr: ["view","export"],
    security: ["view","export"],
    logistics: ["view","export"],
    kpis: ["view","create","update","delete","measure"],
    builder: ["view","create","update","delete","run"],
    saved: ["view","create","update","delete","schedule"],
  },
  admin: {
    users: ["view","create","update","delete","disable","enable","reset_password","assign_roles","activate","suspend","invite","view_sessions","revoke_sessions"],
    roles: ["view","create","update","delete"],
    permissions: ["view","assign"],
    policies: ["view","create","update","delete","activate"],
    sod: ["view","create","update","delete","activate"],
    settings: ["view","update"],
    imports: ["view","run","download_template"],
    exports: ["view","run"],
    audit: ["view","export"],
    events: ["view"],
    dashboard: ["view"],
    sessions: ["view","revoke"],
    security: ["view"],
    feature_flags: ["view","update"],
    backups: ["view","restore"],
    health: ["view"],
    audit_logs: ["view"],
    company_config: ["administer","update","view"],
    integrations: ["manage","view"],
    notifications: ["update","view"],
    numbering: ["update","view"],
    organization: ["update","view"],
  },
  database: {
    health: ["view"],
    connections: ["view"],
    activity: ["view"],
    performance: ["view"],
    query: ["analyze"],
    schema: ["view","manage"],
    index: ["view","manage"],
    backup: ["view","create","delete"],
    restore: ["request","approve"],
    migration: ["view","execute"],
    integrity: ["run"],
    data_quality: ["view"],
    retention: ["manage"],
    archive: ["manage"],
    audit: ["view"],
    settings: ["manage"],
    locks: ["view"],
    maintenance: ["run"],
  },
};

function buildPermissions() {
  const perms = [];
  for (const [module, resources] of Object.entries(MODULES)) {
    for (const [resource, actions] of Object.entries(resources)) {
      for (const action of actions) {
        perms.push({
          code: `${module}.${resource}.${action}`,
          module,
          resource,
          action,
          description: `${action} ${resource} (${module})`,
          is_system: false,
        });
      }
    }
  }
  return perms;
}

// Role catalogue per the ERP spec (section 9).
// grants use wildcards: "*" = everything, "module.*" = module, "module.resource.*" = resource.
const ROLES = [
  // Administration
  { code: "super_administrator", name: "Super Administrator", grants: ["*"] },
  { code: "system_administrator", name: "System Administrator", grants: ["admin.*", "database.*", "settings", "workflows.*", "reports.*", "expenditure.*"] },
  { code: "security_administrator", name: "Security Administrator", grants: ["admin.users.*", "admin.roles.*", "admin.permissions.*", "admin.policies.*", "admin.sod.*", "admin.audit.*", "qr.*", "security_printing.audit.*"] },
  { code: "it_support_administrator", name: "IT Support Administrator", grants: ["admin.users.view", "admin.settings.*", "documents.*"] },
  { code: "integration_administrator", name: "Integration Administrator", grants: ["admin.imports.*", "admin.exports.*", "admin.events.*", "admin.integrations.*", "admin.settings.view"] },
  { code: "backup_administrator", name: "Backup Administrator", grants: ["admin.settings.view", "admin.audit.view"] },
  { code: "audit_administrator", name: "Audit Administrator", grants: ["admin.audit.*", "admin.events.*", "reports.*"] },
  // Executive
  { code: "ceo", name: "CEO", grants: ["*", "!admin.users.*", "!admin.roles.*", "!admin.permissions.*", "!admin.policies.*", "!admin.sod.*", "!admin.security.*", "!admin.sessions.*"] },
  { code: "managing_director", name: "Managing Director", grants: ["*", "!admin.users.*", "!admin.roles.*", "!admin.permissions.*", "!admin.policies.*", "!admin.sod.*", "!admin.security.*", "!admin.sessions.*"] },
  { code: "executive_director", name: "Executive Director", grants: ["*", "!admin.users.*", "!admin.roles.*", "!admin.permissions.*", "!admin.policies.*", "!admin.sod.*", "!admin.security.*", "!admin.sessions.*"] },
  { code: "general_manager", name: "General Manager", grants: ["*", "!admin.users.*", "!admin.roles.*", "!admin.permissions.*", "!admin.policies.*", "!admin.sod.*", "!admin.security.*", "!admin.sessions.*"] },
  { code: "operations_director", name: "Operations Director", grants: ["production.*", "quality.*", "maintenance.*", "inventory.*", "procurement.*", "expenditure.*", "workflows.instances.*", "reports.*"] },
  { code: "cfo", name: "CFO", grants: ["finance.*", "expenditure.*", "procurement.payments.*", "workflows.instances.*", "reports.finance.*", "reports.executive.*", "hr.final_settlements.view", "hr.final_settlements.approve", "hr.final_settlements.pay", "hr.final_settlements.export"] },
  { code: "commercial_director", name: "Commercial Director", grants: ["crm.*", "sales.*", "expenditure.*", "reports.sales.*", "reports.executive.*"] },
  { code: "hr_director", name: "HR Director", grants: ["hr.*", "reports.hr.*", "reports.dashboards.view"] },
  // Finance
  { code: "finance_manager", name: "Finance Manager", grants: ["finance.*", "expenditure.*", "procurement.supplier_invoices.*", "procurement.payments.*", "workflows.instances.*", "reports.finance.*", "hr.final_settlements.view", "hr.final_settlements.approve", "hr.final_settlements.pay"] },
  { code: "chief_accountant", name: "Chief Accountant", grants: ["finance.*", "expenditure.*", "workflows.instances.*", "reports.finance.*"] },
  { code: "financial_controller", name: "Financial Controller", grants: ["finance.*", "reports.finance.*", "procurement.supplier_invoices.view", "sales.invoices.view"] },
  { code: "accountant", name: "Accountant", grants: ["finance.chart_of_accounts.*", "finance.journals.*", "finance.banks.*", "finance.expenses.*", "finance.advances.*", "finance.taxes.*", "finance.periods.view", "finance.reports.view", "finance.posting_rules.*", "finance.templates.*", "finance.tax_jurisdictions.*", "finance.tax_rules.*", "finance.tax_transactions.*", "finance.efris.*", "finance.budget_revisions.view", "finance.budget_commitments.view", "finance.allocation_rules.*", "finance.production_costs.*", "finance.intercompany.view", "finance.consolidation.view", "finance.close_tasks.view", "finance.audit.view"] },
  { code: "ar_officer", name: "AR Officer", grants: ["sales.invoices.*", "sales.receipts.*", "sales.credit_notes.*", "sales.debit_notes.*", "sales.statements.*", "finance.banks.view", "finance.journals.view", "reports.finance.view"] },
  { code: "ap_officer", name: "AP Officer", grants: ["procurement.supplier_invoices.*", "procurement.payments.view", "finance.banks.view", "finance.journals.view"] },
  { code: "cashier", name: "Cashier", grants: ["sales.receipts.view", "sales.receipts.create", "sales.receipts.post", "finance.banks.view", "finance.journals.view"] },
  { code: "treasury_officer", name: "Treasury Officer", grants: ["finance.banks.*", "finance.journals.view", "procurement.payments.view", "sales.receipts.view", "finance.efris.view", "finance.intercompany.*", "finance.consolidation.view", "finance.production_costs.view", "finance.close_tasks.view", "finance.tax_transactions.view"] },
  { code: "budget_officer", name: "Budget Officer", grants: ["finance.budgets.*", "finance.budget_revisions.*", "finance.budget_commitments.*", "finance.posting_rules.view", "finance.reports.view", "reports.finance.view"] },
  { code: "tax_officer", name: "Tax Officer", grants: ["finance.taxes.*", "finance.reports.*", "finance.tax_jurisdictions.*", "finance.tax_rules.*", "finance.tax_transactions.*", "finance.efris.*", "finance.journals.view"] },
  { code: "payroll_accountant", name: "Payroll Accountant", grants: ["hr.payrolls.*", "hr.employees.view", "hr.leave.view", "finance.journals.view"] },
  { code: "internal_auditor", name: "Internal Auditor", grants: ["admin.audit.*", "finance.reports.*", "inventory.stock.view", "procurement.orders.view", "sales.invoices.view", "reports.*", "finance.audit.view", "finance.journals.view", "finance.efris.view", "finance.tax_transactions.view", "finance.production_costs.view", "finance.close_tasks.view", "finance.consolidation.view"] },
  // Sales / CRM
  { code: "sales_director", name: "Sales Director", grants: ["crm.*", "sales.*", "reports.sales.*"] },
  { code: "sales_manager", name: "Sales Manager", grants: ["crm.*", "sales.quotations.*", "sales.orders.*", "sales.delivery_notes.*", "sales.returns.*", "workflows.instances.*", "reports.sales.view"] },
  { code: "sales_executive", name: "Sales Executive", grants: ["crm.leads.*", "crm.customers.*", "crm.contacts.*", "crm.opportunities.*", "crm.activities.*", "sales.quotations.view", "sales.quotations.create", "sales.quotations.submit", "sales.quotations.print", "sales.orders.view"] },
  { code: "sales_representative", name: "Sales Representative", grants: ["crm.leads.view", "crm.leads.create", "crm.leads.update", "crm.activities.*", "crm.customers.view"] },
  { code: "crm_manager", name: "CRM Manager", grants: ["crm.*", "reports.sales.view"] },
  { code: "crm_officer", name: "CRM Officer", grants: ["crm.leads.*", "crm.customers.view", "crm.contacts.*", "crm.activities.*"] },
  { code: "account_manager", name: "Account Manager", grants: ["crm.customers.view", "crm.contacts.*", "crm.activities.*", "crm.complaints.*", "sales.orders.view", "sales.invoices.view"] },
  { code: "customer_service_officer", name: "Customer Service Officer", grants: ["crm.customers.view", "crm.contacts.*", "crm.complaints.*", "crm.activities.*"] },
  { code: "sales_coordinator", name: "Sales Coordinator", grants: ["sales.quotations.view", "sales.orders.view", "sales.delivery_notes.view", "crm.activities.*"] },
  // Procurement
  { code: "procurement_director", name: "Procurement Director", grants: ["procurement.*", "reports.procurement.*"] },
  { code: "procurement_manager", name: "Procurement Manager", grants: ["procurement.*", "expenditure.*", "workflows.instances.*"] },
  { code: "procurement_officer", name: "Procurement Officer", grants: ["procurement.suppliers.*", "procurement.requisitions.*", "procurement.rfqs.*", "procurement.quotations.*", "procurement.orders.create", "procurement.orders.update", "procurement.orders.submit", "procurement.orders.print", "procurement.contracts.*"] },
  { code: "purchasing_officer", name: "Purchasing Officer", grants: ["procurement.requisitions.*", "procurement.orders.view", "procurement.orders.create", "procurement.orders.submit", "procurement.rfqs.*"] },
  { code: "procurement_assistant", name: "Procurement Assistant", grants: ["procurement.requisitions.view", "procurement.rfqs.view", "procurement.orders.view"] },
  { code: "supplier_relationship_manager", name: "Supplier Relationship Manager", grants: ["procurement.suppliers.*", "procurement.contracts.*", "procurement.supplier_invoices.view"] },
  { code: "procurement_evaluator", name: "Procurement Evaluator", grants: ["procurement.quotations.evaluate", "procurement.quotations.select", "procurement.suppliers.evaluate", "procurement.rfqs.view"] },
  { code: "procurement_approver", name: "Procurement Approver", grants: ["procurement.orders.view", "procurement.orders.approve", "procurement.requisitions.view", "procurement.requisitions.approve", "procurement.suppliers.view", "procurement.suppliers.approve"] },
  // Warehouse
  { code: "supply_chain_manager", name: "Supply Chain Manager", grants: ["inventory.*", "procurement.*", "logistics.*", "reports.inventory.*"] },
  { code: "warehouse_manager", name: "Warehouse Manager", grants: ["inventory.*", "logistics.deliveries.*", "workflows.instances.*", "quality.inspections.view", "procurement.orders.view", "procurement.goods_receipts.view", "procurement.goods_receipts.create", "sales.orders.view", "sales.orders.allocate", "sales.orders.dispatch", "sales.delivery_notes.view", "production.work_orders.view", "production.work_orders.issue"] },
  { code: "warehouse_supervisor", name: "Warehouse Supervisor", grants: ["inventory.items.*", "inventory.stock.*", "inventory.movements.*", "inventory.transfers.*", "inventory.adjustments.submit", "inventory.bins.*", "qr.scan.*", "procurement.goods_receipts.view", "sales.orders.view", "production.work_orders.view", "inventory.counts.*", "inventory.quality_holds.view", "inventory.quality_holds.create", "inventory.handling_units.*", "inventory.allocations.*", "inventory.ledger.view", "inventory.traceability.view", "inventory.alerts.view", "inventory.alerts.acknowledge", "inventory.putaway.*", "inventory.receiving.*", "inventory.picking.*", "inventory.packing.*", "inventory.dispatch.*", "inventory.zones.view", "inventory.racks.view", "inventory.shelves.view"] },
  { code: "storekeeper", name: "Storekeeper", grants: ["inventory.items.view", "inventory.stock.view", "inventory.movements.create", "inventory.reservations.*", "inventory.bins.view", "qr.scan.*", "inventory.transfers.view", "procurement.goods_receipts.view", "sales.orders.view", "inventory.ledger.view", "inventory.counts.view", "inventory.counts.create", "inventory.counts.enter", "inventory.handling_units.view", "inventory.traceability.view", "inventory.alerts.view", "inventory.putaway.execute", "inventory.putaway.confirm", "inventory.receiving.view", "inventory.picking.execute", "inventory.packing.execute", "inventory.dispatch.view"] },
  { code: "inventory_controller", name: "Inventory Controller", grants: ["inventory.items.*", "inventory.stock.*", "inventory.batches.*", "inventory.reservations.*", "inventory.adjustments.view", "reports.inventory.view", "inventory.ledger.view", "inventory.counts.view", "inventory.counts.schedule", "inventory.valuations.view", "inventory.forecasts.view", "inventory.risk.view", "inventory.alerts.view", "inventory.traceability.view", "inventory.reorder_recommendations.view"] },
  { code: "inventory_officer", name: "Inventory Officer", grants: ["inventory.items.*", "inventory.stock.*", "inventory.movements.*", "inventory.batches.*"] },
  { code: "receiving_officer", name: "Receiving Officer", grants: ["procurement.goods_receipts.*", "inventory.items.view", "inventory.stock.view", "qr.scan.*"] },
  { code: "dispatch_officer", name: "Dispatch Officer", grants: ["sales.delivery_notes.*", "logistics.deliveries.*", "inventory.stock.view", "qr.scan.*", "qr.codes.view"] },
  { code: "stock_auditor", name: "Stock Auditor", grants: ["inventory.stock.view", "inventory.adjustments.*", "inventory.movements.view", "reports.inventory.view", "admin.audit.view"] },
  { code: "stock_counter", name: "Stock Counter", grants: ["inventory.stock.view", "inventory.adjustments.create", "inventory.adjustments.submit", "qr.scan.*"] },
  // Production
  { code: "production_director", name: "Production Director", grants: ["production.*", "quality.*", "maintenance.*", "inventory.stock.view", "reports.production.*"] },
  { code: "production_manager", name: "Production Manager", grants: ["production.*", "quality.inspections.view", "maintenance.requests.*", "reports.production.view"] },
  { code: "production_planner", name: "Production Planner", grants: ["production.plans.*", "production.work_orders.view", "production.work_orders.create", "production.work_orders.submit", "production.boms.view", "production.routings.view", "inventory.stock.view", "demand"] },
  { code: "production_supervisor", name: "Production Supervisor", grants: ["production.work_orders.*", "production.outputs.*", "production.downtime.*", "production.machines.view", "quality.inspections.execute", "inventory.items.view", "inventory.movements.create"] },
  { code: "production_officer", name: "Production Officer", grants: ["production.work_orders.view", "production.work_orders.update", "production.outputs.*", "production.downtime.*"] },
  { code: "work_order_manager", name: "Work Order Manager", grants: ["production.work_orders.*", "production.plans.view", "production.costing.view"] },
  { code: "production_scheduler", name: "Production Scheduler", grants: ["production.plans.*", "production.work_orders.view", "production.work_orders.update", "production.machines.view"] },
  { code: "machine_operator", name: "Machine Operator", grants: ["production.work_orders.view", "production.work_orders.start", "production.work_orders.record", "production.outputs.create", "production.downtime.create", "production.machines.view", "qr.scan.*", "quality.inspections.view"] },
  { code: "production_cost_analyst", name: "Production Cost Analyst", grants: ["production.costing.*", "production.work_orders.view", "reports.production.*"] },
  // Maintenance
  { code: "maintenance_manager", name: "Maintenance Manager", grants: ["maintenance.*", "production.machines.view", "inventory.items.view"] },
  { code: "maintenance_supervisor", name: "Maintenance Supervisor", grants: ["maintenance.*", "production.machines.view"] },
  { code: "maintenance_technician", name: "Maintenance Technician", grants: ["maintenance.requests.view", "maintenance.requests.update", "maintenance.work_orders.*", "production.machines.view", "qr.scan.*"] },
  { code: "electrical_technician", name: "Electrical Technician", grants: ["maintenance.work_orders.*", "maintenance.requests.view", "production.machines.view"] },
  { code: "mechanical_technician", name: "Mechanical Technician", grants: ["maintenance.work_orders.*", "maintenance.requests.view", "production.machines.view"] },
  { code: "machine_controller", name: "Machine Controller", grants: ["production.machines.*", "maintenance.requests.*", "maintenance.schedules.view"] },
  { code: "maintenance_planner", name: "Maintenance Planner", grants: ["maintenance.schedules.*", "maintenance.requests.view", "production.machines.view"] },
  // Quality
  { code: "quality_director", name: "Quality Director", grants: ["quality.*", "production.work_orders.view", "reports.quality.*"] },
  { code: "quality_manager", name: "Quality Manager", grants: ["quality.*", "production.work_orders.view", "reports.quality.view"] },
  { code: "quality_supervisor", name: "Quality Supervisor", grants: ["quality.plans.*", "quality.inspections.*", "quality.defects.*", "quality.ncrs.*", "quality.capa.*"] },
  { code: "quality_inspector", name: "Quality Inspector", grants: ["quality.inspections.*", "quality.results.*", "quality.defects.*", "quality.ncrs.view", "qr.scan.*", "inventory.stock.view"] },
  { code: "qc_officer", name: "QC Officer", grants: ["quality.inspections.view", "quality.inspections.execute", "quality.results.*", "quality.defects.*"] },
  { code: "ncr_officer", name: "NCR Officer", grants: ["quality.ncrs.*", "quality.capa.*"] },
  { code: "qa_auditor", name: "QA Auditor", grants: ["quality.inspections.view", "quality.ncrs.view", "quality.capa.view", "reports.quality.view", "admin.audit.view"] },
  // Security printing
  { code: "security_printing_director", name: "Security Printing Director", grants: ["security_printing.*", "qr.*", "quality.*", "reports.security.*"] },
  { code: "security_printing_manager", name: "Security Printing Manager", grants: ["security_printing.*", "qr.codes.*", "qr.labels.*", "qr.reams.*", "qr.cartons.*", "qr.packing.*", "reports.security.view"] },
  { code: "security_production_supervisor", name: "Security Production Supervisor", grants: ["security_printing.jobs.*", "security_printing.custody.*", "security_printing.batches.*", "security_printing.operators.*", "security_printing.machines.*", "qr.scan.*", "qr.packing.*"] },
  { code: "security_printing_officer", name: "Security Printing Officer", grants: ["security_printing.jobs.view", "security_printing.jobs.create", "security_printing.jobs.update", "security_printing.custody.view", "security_printing.custody.record"] },
  { code: "secure_machine_operator", name: "Secure Machine Operator", grants: ["security_printing.jobs.view", "security_printing.jobs.update", "security_printing.custody.record", "production.work_orders.view", "production.outputs.create", "qr.scan.*"] },
  { code: "secure_materials_controller", name: "Secure Materials Controller", grants: ["security_printing.jobs.view", "security_printing.jobs.issue_materials", "security_printing.custody.record", "inventory.stock.view"] },
  { code: "secure_stock_controller", name: "Secure Stock Controller", grants: ["security_printing.batches.*", "security_printing.jobs.view", "inventory.stock.view", "qr.codes.view", "qr.labels.create"] },
  { code: "spoilage_controller", name: "Spoilage Controller", grants: ["security_printing.jobs.view", "security_printing.jobs.update", "security_printing.batches.*", "quality.defects.*", "quality.ncrs.view"] },
  { code: "security_printing_auditor", name: "Security Printing Auditor", grants: ["security_printing.audit.*", "security_printing.custody.view", "security_printing.jobs.view", "admin.audit.view", "reports.security.view"] },
  { code: "secure_job_approver", name: "Secure Job Approver", grants: ["security_printing.jobs.view", "security_printing.jobs.approve", "security_printing.jobs.reject", "security_printing.jobs.authorize_materials", "security_printing.jobs.reconcile", "workflows.instances.view", "workflows.instances.approve", "workflows.instances.reject", "workflows.instances.return", "dashboard.*", "reports.executive.view", "notifications.notifications.*"] },
  // HR
  { code: "hr_manager", name: "HR Manager", grants: ["hr.*", "workflows.instances.*"] },
  { code: "hr_officer", name: "HR Officer", grants: ["hr.employees.*", "hr.contracts.*", "hr.certificates.*", "hr.legal_rules.view", "hr.attendance.*", "hr.leave.*", "hr.loans.*", "hr.divisions.*", "hr.locations.*", "hr.org_units.*", "hr.teams.*", "hr.job_families.*", "hr.job_grades.*", "hr.positions.*", "hr.position_assignments.*", "hr.workforce_plans.*", "hr.shifts.*", "hr.shift_assignments.*", "hr.timesheets.*", "hr.overtime.*", "hr.leave_types.*", "hr.leave_policies.*", "hr.leave_accruals.*", "hr.leave_balances.*", "hr.holidays.*", "hr.benefit_plans.*", "hr.benefit_enrollments.*", "hr.benefit_claims.*", "hr.grievances.*", "hr.investigations.*", "hr.disciplinary.*", "hr.warnings.*", "hr.asset_assignments.*", "hr.employee_requests.*", "hr.projects.*", "hr.onboarding.*", "hr.offboardings.*", "hr.alumni.view", "hr.payroll_components.view", "hr.employee_salaries.view", "hr.employee_earnings.view", "hr.employee_deductions.view", "hr.employee_benefits.view", "hr.overtime_records.view", "hr.bonus_records.view", "hr.commission_records.view", "hr.final_settlements.view", "hr.final_settlements.create", "hr.final_settlements.update", "hr.final_settlements.submit"] },
  { code: "hr_assistant", name: "HR Assistant", grants: ["hr.employees.view", "hr.employees.create", "hr.attendance.*", "hr.leave.view", "hr.positions.view", "hr.onboarding.*", "hr.offboardings.view", "hr.alumni.view", "hr.employee_requests.*", "hr.leave_types.view", "hr.holidays.view", "hr.asset_assignments.view", "hr.employee_identity.view", "hr.employee_card.view", "hr.employee_qr.view", "hr.employee_assignments.view"] },
  { code: "recruitment_officer", name: "Recruitment Officer", grants: ["hr.requisitions.*", "hr.vacancies.*", "hr.vacancy_channels.*", "hr.candidates.*", "hr.applications.*", "hr.interviews.*", "hr.assessments.*", "hr.offers.*", "hr.onboarding.view", "hr.positions.view", "hr.workforce_plans.view", "hr.employees.view"] },
  { code: "training_officer", name: "Training Officer", grants: ["hr.training_catalog.*", "hr.training_sessions.*", "hr.training_requests.*", "hr.training_enrollments.*", "hr.training_certificates.*", "hr.competencies.*", "hr.employees.view"] },
  { code: "performance_officer", name: "Performance Officer", grants: ["hr.performance_goals.*", "hr.performance_kpis.*", "hr.performance_reviews.*", "hr.pips.*", "hr.employees.view"] },
  { code: "payroll_manager", name: "Payroll Manager", grants: ["hr.payrolls.view", "hr.payrolls.update", "hr.payrolls.submit", "hr.payrolls.approve", "hr.payrolls.post", "hr.payrolls.print", "hr.payroll_components.*", "hr.employee_salaries.*", "hr.employee_earnings.*", "hr.employee_deductions.*", "hr.employee_benefits.*", "hr.overtime_records.*", "hr.bonus_records.*", "hr.commission_records.*", "hr.statutory_configs.view", "hr.employees.view", "hr.loans.view", "hr.timesheets.view", "hr.overtime.view", "hr.employee_requests.view", "hr.final_settlements.*", "hr.loans.approve", "hr.loans.write_off", "hr.advances.view", "hr.advances.approve", "workflows.instances.*"] },
  { code: "payroll_officer", name: "Payroll Officer", grants: ["hr.payrolls.view", "hr.payrolls.create", "hr.payrolls.update", "hr.payrolls.submit", "hr.payrolls.print", "hr.payroll_components.view", "hr.employee_salaries.view", "hr.employee_salaries.create", "hr.employee_salaries.update", "hr.employee_earnings.view", "hr.employee_earnings.create", "hr.employee_earnings.update", "hr.employee_deductions.view", "hr.employee_deductions.create", "hr.employee_deductions.update", "hr.employee_benefits.view", "hr.employee_benefits.create", "hr.employee_benefits.update", "hr.overtime_records.view", "hr.overtime_records.create", "hr.overtime_records.update", "hr.bonus_records.view", "hr.bonus_records.create", "hr.bonus_records.update", "hr.commission_records.view", "hr.commission_records.create", "hr.commission_records.update", "hr.statutory_configs.view", "hr.timesheets.view", "hr.overtime.view", "hr.employees.view", "hr.final_settlements.view", "hr.final_settlements.create", "hr.final_settlements.update", "hr.final_settlements.submit", "hr.final_settlements.export"] },
  { code: "time_attendance_officer", name: "Time & Attendance Officer", grants: ["hr.attendance.*", "hr.shifts.*", "hr.shift_assignments.*", "hr.timesheets.*", "hr.overtime.*", "hr.holidays.view", "hr.employees.view", "hr.leave.view"] },
  { code: "employee_self_service", name: "Employee Self-Service User", grants: ["hr.leave.view", "hr.leave.create", "hr.attendance.view", "hr.payslips.view", "hr.employee_requests.*", "hr.benefit_plans.view", "hr.benefit_enrollments.view", "hr.training_catalog.view", "hr.training_sessions.view", "hr.competencies.view", "hr.performance_goals.view", "hr.performance_reviews.view", "hr.holidays.view", "hr.contracts.view", "hr.contracts.sign", "hr.contracts.download", "hr.certificates.view", "notifications.notifications.*"] },
  { code: "onboarding_officer", name: "Onboarding Officer", grants: ["hr.onboarding.*", "hr.employees.view", "hr.asset_assignments.*", "hr.positions.view", "hr.employee_requests.view"] },
  { code: "benefits_officer", name: "Benefits Officer", grants: ["hr.benefit_plans.*", "hr.benefit_enrollments.*", "hr.benefit_claims.*", "hr.employee_benefits.*", "hr.employees.view"] },
  { code: "workforce_planner", name: "Workforce Planner", grants: ["hr.workforce_plans.*", "hr.workforce_scenarios.*", "hr.positions.view", "hr.job_families.view", "hr.job_grades.view", "hr.employees.view"] },
  { code: "relations_officer", name: "Employee Relations Officer", grants: ["hr.grievances.*", "hr.investigations.*", "hr.disciplinary.*", "hr.warnings.*", "hr.employees.view"] },
  // Logistics
  { code: "logistics_manager", name: "Logistics Manager", grants: ["logistics.*", "sales.delivery_notes.*", "reports.*"] },
  { code: "logistics_officer", name: "Logistics Officer", grants: ["logistics.trips.*", "logistics.fuel.*", "logistics.fleet.*", "logistics.deliveries.*"] },
  { code: "dispatch_manager", name: "Dispatch Manager", grants: ["sales.delivery_notes.*", "logistics.deliveries.*", "inventory.stock.view", "qr.scan.*"] },
  { code: "fleet_manager", name: "Fleet Manager", grants: ["logistics.vehicles.*", "logistics.fuel.*", "logistics.fleet.*", "logistics.drivers.*", "logistics.routes.*"] },
  { code: "fleet_officer", name: "Fleet Officer", grants: ["logistics.vehicles.view", "logistics.vehicles.update", "logistics.fuel.*", "logistics.fleet.*"] },
  { code: "delivery_coordinator", name: "Delivery Coordinator", grants: ["logistics.deliveries.*", "logistics.trips.view", "sales.delivery_notes.view"] },
  { code: "driver", name: "Driver", grants: ["logistics.trips.view", "logistics.trips.update", "logistics.deliveries.view", "logistics.deliveries.deliver", "qr.scan.*", "sales.delivery_notes.view"] },
  // Assets
  { code: "asset_manager", name: "Asset Manager", grants: ["assets.*", "finance.journals.view", "finance.journals.create", "finance.journals.post", "admin.audit.view"] },
  { code: "asset_officer", name: "Asset Officer", grants: ["assets.register.*", "assets.tags.*", "assets.transfers.*", "assets.movements.*", "assets.assignments.*", "assets.locations.*", "assets.categories.*", "assets.types.*", "assets.classes.*", "assets.maintenance.*", "assets.warranties.*", "assets.insurance.*", "assets.documents.*", "assets.photos.*", "assets.depreciation.*", "assets.scans.*", "assets.timeline.*", "assets.dashboards.*", "assets.reports.*", "assets.imports.*", "assets.exports.*"] },
  { code: "asset_custodian", name: "Asset Custodian", grants: ["assets.register.view", "assets.register.print", "assets.register.scan", "assets.register.verify", "assets.register.comment", "assets.tags.view", "assets.scans.*", "assets.timeline.*", "assets.dashboards.view", "assets.documents.view", "assets.photos.view", "qr.scan.*"] },
  { code: "asset_auditor", name: "Asset Auditor", grants: ["assets.register.view", "assets.register.audit", "assets.register.verify", "assets.register.scan", "assets.audits.*", "assets.audit_items.*", "assets.anomalies.*", "assets.movements.view", "assets.scans.*", "assets.timeline.*", "assets.dashboards.view", "assets.reports.view", "admin.audit.view"] },
  { code: "asset_storekeeper", name: "Asset Storekeeper", grants: ["assets.register.view", "assets.register.scan", "assets.register.verify", "assets.register.checkin", "assets.register.checkout", "assets.register.comment", "assets.tags.view", "assets.tags.print", "assets.locations.view", "assets.scans.*", "assets.timeline.*", "assets.dashboards.view", "qr.scan.*"] },
  { code: "asset_finance", name: "Asset Finance Officer", grants: ["assets.register.view", "assets.register.capitalize", "assets.register.depreciate", "assets.register.impair", "assets.depreciation.*", "assets.impairments.*", "assets.disposals.*", "assets.reports.*", "assets.exports.*", "finance.journals.view", "finance.journals.post"] },
  // Analytics
  { code: "bi_manager", name: "BI Manager", grants: ["reports.*", "admin.exports.*", "admin.imports.*"] },
  { code: "data_analyst", name: "Data Analyst", grants: ["reports.*", "admin.exports.*"] },
  { code: "reporting_officer", name: "Reporting Officer", grants: ["reports.view", "reports.sales.view", "reports.procurement.view", "reports.inventory.view", "reports.production.view", "reports.finance.view", "reports.export", "reports.builder.view", "reports.builder.run", "reports.kpis.view"] },
  { code: "executive_viewer", name: "Executive Viewer", grants: ["reports.dashboards.view", "reports.dashboards.create", "reports.executive.view", "dashboard.*"] },
  { code: "department_analyst", name: "Department Analyst", grants: ["reports.view", "reports.export", "reports.builder.view", "reports.builder.run", "reports.kpis.view"] },
  // Healthcare
  { code: "healthcare_admin", name: "Healthcare Administrator", grants: ["healthcare.*", "inventory.stock.view", "reports.healthcare.*", "admin.audit.view"] },
  { code: "doctor", name: "Doctor", grants: ["healthcare.patients.*", "healthcare.visits.*", "healthcare.appointments.*", "healthcare.emrs.*", "healthcare.diagnoses.*", "healthcare.vitals.*", "healthcare.observations.*", "healthcare.prescriptions.*", "healthcare.lab_requests.*", "healthcare.lab_results.view", "healthcare.practitioners.view", "qr.scan.*", "reports.healthcare.view", "notifications.notifications.*"] },
  { code: "nurse", name: "Nurse", grants: ["healthcare.patients.view", "healthcare.patients.create", "healthcare.patients.update", "healthcare.visits.*", "healthcare.appointments.*", "healthcare.vitals.*", "healthcare.observations.*", "healthcare.prescriptions.view", "healthcare.lab_requests.create", "healthcare.beds.view", "healthcare.wards.view", "qr.scan.*"] },
  { code: "pharmacist", name: "Pharmacist", grants: ["healthcare.prescriptions.*", "healthcare.dispensings.*", "inventory.stock.view", "inventory.items.view", "inventory.batches.view", "inventory.movements.view", "qr.scan.*", "reports.healthcare.view"] },
  { code: "lab_technician", name: "Lab Technician", grants: ["healthcare.lab_requests.*", "healthcare.lab_results.*", "healthcare.patients.view", "inventory.items.view", "inventory.stock.view", "qr.scan.*"] },
  { code: "receptionist", name: "Receptionist", grants: ["healthcare.patients.*", "healthcare.visits.create", "healthcare.visits.update", "healthcare.visits.view", "healthcare.appointments.*", "healthcare.bills.view", "crm.customers.view", "qr.scan.*", "notifications.notifications.*"] },
  { code: "insurance_officer", name: "Insurance Officer", grants: ["healthcare.insurance_payers.*", "healthcare.insurance_claims.*", "healthcare.bills.view", "healthcare.patients.view", "healthcare.visits.view", "reports.healthcare.view"] },
  { code: "medical_auditor", name: "Medical Auditor", grants: ["healthcare.patients.view", "healthcare.visits.view", "healthcare.emrs.view", "healthcare.prescriptions.view", "healthcare.dispensings.view", "healthcare.lab_requests.view", "healthcare.lab_results.view", "healthcare.insurance_claims.view", "healthcare.bills.view", "admin.audit.view", "reports.healthcare.view"] },
  { code: "ward_nurse", name: "Ward Nurse", grants: ["healthcare.beds.view", "healthcare.beds.assign", "healthcare.beds.release", "healthcare.visits.view", "healthcare.visits.admit", "healthcare.visits.discharge", "healthcare.vitals.*", "healthcare.observations.*", "healthcare.patients.view", "qr.scan.*"] },
];


module.exports = { ACTIONS, MODULES, buildPermissions, ROLES };
